import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Lang = 'en' | 'ja';

const en = {
  // App
  appTitle: 'Content Creator Studio — workspace',
  appLoading: 'Loading…',

  // Auth
  authSubtitle: 'Login to access your workspace',
  authEmail: 'Email',
  authPassword: 'Password',
  authPasswordPlaceholder: 'Enter password',
  authLoginBtn: 'Login',
  authLoggingIn: 'Logging in…',
  authErrorEmpty: 'Please enter your email and password',
  authErrorInvalid: 'Incorrect email or password',

  // Titlebar
  titlebarUserMgmt: 'Subscribers',
  titlebarInviteUser: 'Invite User',
  titlebarAccountSettings: 'Account Settings',
  titlebarLogout: 'Logout',
  titlebarWpSettings: 'WordPress Settings',

  // WordPress Config
  wpConfigTitle: 'WordPress Settings',
  wpConfigSubtitle: 'Configure your WordPress site credentials',
  wpConfigLoading: 'Loading…',
  wpConfigConnected: 'Connected',
  wpConfigUrl: 'WordPress Site URL',
  wpConfigUrlHint: 'Your WordPress site root URL (without /wp-json)',
  wpConfigUser: 'WordPress Username',
  wpConfigPassword: 'Application Password',
  wpConfigPasswordHint: 'leave blank to keep current',
  wpConfigPasswordPlaceholder: 'xxxx xxxx xxxx xxxx xxxx xxxx',
  wpConfigPasswordPlaceholderExisting: 'Leave blank to keep current password',
  wpConfigPasswordGuide: 'Generate at WP Admin → Users → Application Passwords',
  wpConfigTestBtn: 'Test Connection',
  wpConfigTesting: 'Testing…',
  wpConfigTestOk: 'Connection successful',
  wpConfigTestFail: 'Connection failed',
  wpConfigDeleteBtn: 'Remove',
  wpConfigDeleting: 'Removing…',
  wpConfigDeleted: 'WordPress config removed',
  wpConfigCancel: 'Cancel',
  wpConfigSaveBtn: 'Save',
  wpConfigSaving: 'Saving…',
  wpConfigSaved: 'WordPress settings saved',
  wpConfigErrRequired: 'Site URL and username are required',
  wpConfigErrPasswordRequired: 'Application password is required for first setup',
  wpConfigErrSaveFailed: 'Failed to save settings',
  wpConfigErrDeleteFailed: 'Failed to remove settings',

  // Statusbar
  statusbarSynced: 'Synced',

  // Topic Creator
  topicLoading: 'Loading…',
  topicBreadcrumb: 'Topic Creator',
  topicAiFlowTitle: 'AI Keyword Generation Flow',
  topicStep1Title: 'Extracting worries',
  topicStep1Desc: 'Extracting "unverbalized worries" from search terms',
  topicStep2Title: 'Original KW selection',
  topicStep2Desc: "Select unique keywords that match your blog's identity",
  topicStep3Title: 'Title Generation',
  topicStep3Desc: 'Create compelling article titles that will attract clicks',
  topicSelectKeyword: 'Select a keyword from the left sidebar',
  topicSelectHint: 'Top Level → Expand Keyword → Edit Settings → Generate AI',
  topicNewProject: 'New Project',
  topicNewKeyword: 'New keyword',

  // Stats cards
  statsTotal: 'Total',
  statsKwDone: 'KW Done',
  statsPersonaDone: 'Persona Done',
  statsStructDone: 'Struct Done',

  // Flow Steps
  flowStep01: 'STEP 01',
  flowStep01Label: 'Keyword Generation',
  flowStep02: 'STEP 02',
  flowStep02Label: 'Persona & Structure',
  flowStep03: 'STEP 03',
  flowStep03Label: 'Fact Check',
  flowAll: 'ALL',
  flowAllLabel: 'Show All',

  // Toast messages
  toastTopicLoadFailed: 'Failed to load topics',
  toastTopicCreated: 'Topic created',
  toastTopicCreateFailed: 'Failed to create topic',
  toastRenameFailed: 'Failed to rename',
  toastTopicDeleteConfirm: 'Delete this topic?',
  toastTopicDeleted: 'Topic deleted',
  toastDeleteFailed: 'Failed to delete',
  toastKwAdded: 'Keyword added',
  toastKwAddFailed: 'Failed to add keyword',
  toastUpdateFailed: 'Failed to update',
  toastResultDeleted: 'Deleted',
  toastGenerateFailed: 'Failed to generate',
  toastPersonaGenerating: 'Generating persona & structure…',
  toastPersonaDone: 'Persona & structure generated',
  toastPersonaFailed: 'Persona generation failed',
  toastFactCheckRunning: 'Running fact check…',
  toastFactCheckDone: 'Fact check complete',
  toastFactCheckFailed: 'Fact check failed',
  toastSkipped: 'Skipped',
  toastRestored: 'Restored',
  toastSkipFailed: 'Failed to skip',
  toastRestoreFailed: 'Failed to restore',
  toastFieldRegenDone: 'Field regenerated',
  toastFieldRegenFailed: 'Failed to regenerate field',
  toastArticleGenerating: 'Generating article…',
  toastArticleDone: 'Article generated',
  toastArticleFailed: 'Article generation failed',
  toastSectionRegenDone: 'Section regenerated',
  toastImageGenDone: 'Image generated',
  toastImageGenFailed: 'Image generation failed',
  toastPublishDone: 'Published successfully',
  toastPublishFailed: 'Publish failed',

  // Topic Tree
  treeHeader: '📋 Topic Settings',
  treeCollapseAll: 'Collapse all',
  treeAddTop: 'Add top level',
  treeEdit: 'Edit',
  treeDelete: 'Delete',
  treeWpConfig: 'WordPress Settings',
  treeAddKeyword: 'Add Keywords...',

  // Keyword Card
  kwKeyword: 'Keyword',
  kwGoal: 'Content Goal',
  kwGoalPlaceholder: 'e.g. Help readers understand X and take action',
  kwAudience: 'Target Audience',
  kwGenerating: 'Generating...',
  kwGenerate: 'AI-powered keyword and title generation',
  kwViewResults: 'Showing results',

  // Results Table
  resultsEmpty: 'No keywords generated yet',
  resultsEmptyHint: 'Click "AI-powered keyword and title generation" in the sidebar',
  resultsSearch: 'search...',
  resultsAll: 'all',
  resultsColKeyword: 'Keyword',
  resultsColTitle: 'Title',
  resultsColStatus: 'Status',
  resultsColAction: 'Action',
  resultsColDemographic: 'Demographic',
  resultsColPersona1: 'Persona 1',
  resultsColPersona2: 'Persona 2',
  resultsColPersona3: 'Persona 3',
  resultsColDemoSize1: 'Est. Demo Size ①',
  resultsColDemoSize2: 'Est. Demo Size ②',
  resultsColDemoSize3: 'Est. Demo Size ③',
  resultsColFactCheck: 'Fact Check',
  resultsColTargetDecision: 'Demo Decision Reason',
  resultsColStructIntro: 'Intro',
  resultsColStructNayami: 'Problem',
  resultsColStructP1: 'Point 1',
  resultsColStructP2: 'Point 2',
  resultsColStructP3: 'Point 3',
  resultsColStructCommon: 'Common',
  resultsColStructCta: 'CTA',
  resultsColStructMatome: 'Summary',
  resultsColStructH2: 'H2 Keys',
  resultsEdit: 'Edit',
  resultsDelete: 'Delete',

  // Gate buttons
  gatePending: 'Pending',
  gateNextStep: '▶ Next Step',
  gateSkipTitle: '✕ Skip this title',
  gateGenerating: '⏳ Generating…',
  gateFactCheck: '🔍 Run Fact Check',
  gateSkipDemoSize: '✕ Skip demo size',
  gateRunningFC: '⏳ Running FC…',
  gateDone: '✓ Done',
  gatePublished: '🌐 Published',
  gateRestore: '↩ Restore',

  // Status labels
  statusDraft: 'draft',
  statusReady: 'ready',
  statusKwDone: 'kw done',
  statusPersonaWip: 'persona…',
  statusPersonaDone: 'persona ok',
  statusStructWip: 'checking…',
  statusStructDone: 'struct ok',
  statusPublished: 'published',
  statusSkipped: 'skipped',
  // Keep old keys for backward compatibility
  statusProgress: 'in progress',
  statusDone: 'completion',

  // Detail Panel
  detailPanelAll: 'All',
  detailPanelPersona: 'Persona',
  detailPanelStructure: 'Structure',
  detailPanelComment: 'Comment',
  detailPersonaSection: 'Persona & Demographics',
  detailStructSection: 'Article Structure',
  detailFactCheckSection: 'Fact Check Results',
  detailGeneratePersonaBtn: '✨ Generate Persona & Structure',
  detailGeneratePersonaHint: 'No persona data yet. Click to generate.',
  detailSaveBtn: 'Save',
  detailCancelBtn: 'Cancel',
  detailRegenBtn: '🔄',
  detailCommentPlaceholder: 'Add a comment or instruction…',
  detailRegenWithComment: 'Regenerate with instruction',
  detailTargetField: 'Target field',

  // Bulk Actions
  bulkSelected: 'selected',
  bulkNextStep: 'Next Step',
  bulkChangeStatus: 'Change Status',
  bulkGeneratePersona: 'Generate Persona & Structure',
  bulkFactCheck: 'Run Fact Check',
  bulkDelete: 'Delete',

  // Article Creator
  articleCreatorBreadcrumb: 'Article Creator',
  articleStepA: 'STEP A',
  articleStepALabel: 'Write Article',
  articleStepB: 'STEP B',
  articleStepBLabel: 'Generate Images',
  articleStepC: 'STEP C',
  articleStepCLabel: 'Upload',
  articleSidebarHeader: 'Articles',
  articleNoItems: 'No STRUCT_DONE items yet',
  articleNoItemsHint: 'Complete STEP 03 in Topic Creator first',
  articleReferenceBtn: 'Refer to Persona and Structure',
  articleGenerateBtn: 'Generate Article',
  articleGenerating: 'Generating article…',
  articlePreviewBtn: 'Preview',
  articleNextToImages: 'Article OK → Proceed to images',
  articleBackToEdit: '← Back to article',
  articleNextToUpload: 'Images OK → Proceed to upload',
  articleBackToImages: '← Back to images',
  articlePublishBtn: 'Publish',
  articlePublished: 'Published successfully!',
  articlePublishedMsg: 'This article has been published successfully',

  // Section Card
  sectionRegenBtn: 'Regenerate this section',
  sectionRegenWithInstruction: 'Directed regeneration',
  sectionInstructionPlaceholder: 'Enter regeneration instructions…',
  sectionHeadingRegenBtn: 'Regenerate heading',
  sectionHeadingClickToEdit: 'Click to edit',
  toastHeadingRegenDone: 'Heading regenerated',

  // Image Card
  imageTastePhoto: 'Photo',
  imageTasteTextOverlay: 'Text Overlay',
  imageTasteInfographic: 'Infographic',
  imageTasteIllustration: 'Illustration',
  imageTasteCinematic: 'Cinematic',
  imageEnableBtn: 'Enable',
  imageDisableBtn: 'Disable',
  imageGenBtn: 'Generate Image',
  imageRegenBtn: 'Regenerate',
  imagePromptLabel: 'Prompt',
  imagePromptReset: 'Reset',
  imageGenAll: 'Generate All Images',
  imageGenAllBtn: 'Generate all enabled images',

  // Upload Panel
  uploadTabPreview: 'Preview',
  uploadTabSeo: 'SEO & Meta',
  uploadTabPlatform: 'Post Settings',
  uploadSlugLabel: 'Slug (URL)',
  uploadExcerptLabel: 'Excerpt',
  uploadExcerptChars: 'chars',
  uploadTagsLabel: 'Tags',
  uploadCategoryLabel: 'Category',
  uploadPlatformWordPress: 'WordPress',
  uploadPlatformShopify: 'Shopify',
  uploadStatusPublish: 'Publish',
  uploadStatusDraft: 'Draft',
  uploadStatusSchedule: 'Schedule',
  uploadScheduleDate: 'Scheduled date',
  uploadChecklist: 'Pre-publish checklist',
  uploadCheck1: 'Article has been proofread',
  uploadCheck2: 'All images have been generated',
  uploadCheck3: 'SEO information is filled in',
  uploadCheck4: 'Platform has been selected',
  uploadPublishBtn: 'Publish',
  uploadStatsSection: 'Sections',
  uploadStatsChars: 'Total characters',
  uploadStatsImagesGen: 'Generated images',
  uploadStatsImagesEnabled: '有効な画像',

  // Reference Modal
  refModalTitle: 'ペルソナ・構成 参照',
  refTabPersona: 'ペルソナ',
  refTabStructure: '構成',
  refTabDemographics: 'デモグラ',
  refClose: '閉じる',

  // User Modal
  usersTitle: 'SUbscribers',
  usersAddUser: 'Add User',
  usersName: 'Name',
  usersNamePlaceholder: 'John Smith',
  usersEmail: 'Email',
  usersPassword: 'Password',
  usersPasswordPlaceholder: '8+ characters',
  usersRole: 'Role',
  usersAdd: 'Add',
  usersLoading: 'Loading…',
  usersColUser: 'User',
  usersColRole: 'Role',
  usersColStatus: 'Status',
  usersColLastLogin: 'Last Login',
  usersYou: '(You)',
  usersActive: 'Active',
  usersInactive: 'Inactive',
  usersClickRole: 'Click to change role',
  usersDeactivate: 'Deactivate',
  usersActivate: 'Activate',
  usersDeleteBtn: 'Delete',

  // Role labels
  roleAdmin: 'Admin',
  roleEditor: 'Editor',
  roleViewer: 'Viewer',

  // User toast messages
  toastUsersLoadFailed: 'Failed to load users',
  toastUsersFillAll: 'Please fill in all fields',
  toastUsersCreateFailed: 'Failed to create user',
  toastUsersUpdateFailed: 'Failed to update',
  toastUsersRoleChangeFailed: 'Failed to change role',
  toastUsersDeleteFailed: 'Failed to delete',

  // Settings Modal
  settingsTitle: 'Settings',
  settingsSubtitle: 'Password & API key configuration',
  settingsLoading: 'Loading…',
  settingsPassword: 'Password',
  settingsCurrentPassword: 'Current Password',
  settingsNewPassword: 'New Password',
  settingsConfirmPassword: 'Confirm Password',
  settingsChangePassword: 'Change Password',
  settingsPasswordRequired: 'Current and new password are required',
  settingsPasswordMismatch: 'Passwords do not match',
  settingsPasswordTooShort: 'Password must be at least 6 characters',
  settingsPasswordChanged: 'Password changed successfully',
  settingsPasswordFailed: 'Failed to change password',
  settingsSaving: 'Saving…',
  settingsDeleting: 'Removing…',
  settingsKeyConfigured: 'Configured',
  settingsKeyUpdateHint: 'leave blank to keep current',
  settingsKeyEncryptedHint: 'Your key is encrypted and stored securely',
  settingsKeyRequired: 'Please enter an API key',
  settingsSaveKey: 'Save Key',
  settingsKeySaved: 'API key saved',
  settingsKeySaveFailed: 'Failed to save API key',
  settingsRemoveKey: 'Remove Key',
  settingsKeyDeleted: 'API key removed',
  settingsKeyDeleteFailed: 'Failed to remove API key',

  // Video Script
  vsSidebarHeader: 'Video Scripts',
  vsExistingScripts: 'Generated Scripts',
  vsAvailableArticles: 'Available Articles',
  vsNoArticles: 'No articles available for script generation',
  vsSelectArticle: 'Select an article to generate a video script',
  vsNewScript: 'New Video Script',
  vsReadyToGenerate: 'Click Generate to create a video script from this article',
  vsClickGenerate: 'Click "Generate" to create a video script',
  vsGenerate: 'Generate Script',
  vsRegenerate: 'Regenerate',
  vsGenerating: 'Generating script…',
  vsGenerated: 'Video script generated!',
  vsGenFailed: 'Failed to generate video script',
  vsDelete: 'Delete',
  vsDeleted: 'Video script deleted',
  vsDeleteFailed: 'Failed to delete video script',
  vsSections: 'sections',
  vsCreated: 'Created',
  vsHeading: 'Heading',
  vsNarration: 'Narration',
  vsPoints: 'Key Points',
  vsBgKeyword: 'BG Keyword',
  vsSave: 'Save',
  vsCancel: 'Cancel',
  vsSectionSaved: 'Section updated',
  vsSectionSaveFailed: 'Failed to update section',
  vsLoadFailed: 'Failed to load video scripts',
  vsVisualType: 'Visual Type',
  vsVisualNote: 'Visual Note',
  vsEditVisual: 'Edit Visual Content',
  vsImagePrompt: 'Image Prompt',
  vsImagePromptPlaceholder: 'Describe the image you want to generate…',
  vsImageGenerate: 'Generate Image',
  vsImageRegenerate: 'Regenerate',
  vsImageGenerating: 'Generating image…',
  vsImageGenerated: 'Image generated',
  vsImageGenFailed: 'Image generation failed',
  vsImagePromptRequired: 'Please enter an image prompt',
  vsCurrentImage: 'Current Image',

  // TTS
  ttsAudioTitle: 'TTS Audio',
  ttsGenerate: 'Generate Audio',
  ttsRegenerate: 'Regenerate Audio',
  ttsGenerating: 'Generating audio…',
  ttsGenerated: 'Audio generated!',
  ttsGenFailed: 'Failed to generate audio',
  ttsDictBtn: 'Reading Dictionary',
  ttsDictTitle: 'Reading Dictionary (読み替え辞書)',
  ttsDictDesc: 'Add kanji → reading replacements so TTS pronounces words correctly.',
  ttsDictKanji: 'Kanji / Word',
  ttsDictReading: 'Reading',
  ttsDictAdd: 'Add',
  ttsDictEmpty: 'No dictionary entries yet',
  ttsDictLoadFailed: 'Failed to load dictionary',
  ttsDictAddFailed: 'Failed to add entry',
  ttsDictDeleteFailed: 'Failed to delete entry',

  // HeyGen
  heygenTitle: 'HeyGen Avatar Video',
  heygenGenerate: 'Generate Video',
  heygenRegenerate: 'Regenerate Video',
  heygenGenerating: 'Generating…',
  heygenStarted: 'HeyGen video generation started!',
  heygenFailed: 'HeyGen video generation failed',
  heygenCheckStatus: 'Check Status',
  heygenDone: 'HeyGen video ready!',
  heygenStillProcessing: 'Still processing… check again later',
  heygenCheckFailed: 'Failed to check status',
  heygenNeedsTts: 'Generate TTS audio first (Step 1)',

  // Remotion
  remotionTitle: 'Remotion Subtitle Rendering',
  remotionGenerate: 'Start Rendering',
  remotionRegenerate: 'Re-render',
  remotionGenerating: 'Starting render…',
  remotionStarted: 'Remotion rendering started!',
  remotionFailed: 'Remotion rendering failed',
  remotionCheckStatus: 'Check Status',
  remotionDone: 'Final video ready!',
  remotionStillProcessing: 'Still rendering… check again later',
  remotionCheckFailed: 'Failed to check status',
  remotionDownload: 'Download Final Video',
  remotionNeedsHeygen: 'Generate HeyGen video first (Step 2)',

  // Settings
  vsSettings: 'Video Settings',
  vsOrientation: 'Orientation',
  vsAvatar: 'Avatar',
  vsLoadAvatars: 'Load Avatars',
  vsNoAvatars: 'No avatars found in your HeyGen account',
  vsTheme: 'Theme',
  avatarLoadFailed: 'Failed to load avatars',
  settingsSaveFailed: 'Failed to save settings',

  // Shopify Config
  treeShopifyConfig: 'Shopify Settings',
  shopifyConfigTitle: 'Shopify Settings',
  shopifyConfigConnected: 'Connected',
  shopifyConfigDomain: 'Shop Domain',
  shopifyConfigDomainHint: 'e.g. your-store.myshopify.com',
  shopifyConfigToken: 'Access Token',
  shopifyConfigTokenHint: 'leave blank to keep current',
  shopifyConfigTokenPlaceholder: 'shpat_xxxxxxxxxxxxx',
  shopifyConfigTokenPlaceholderExisting: 'Leave blank to keep current token',
  shopifyConfigBlogId: 'Blog ID (optional)',
  shopifyConfigBlogIdHint: 'Leave empty to use default blog',
  shopifyConfigErrDomain: 'Shop domain is required',
  shopifyConfigErrToken: 'Access token is required for first setup',
  shopifyConfigSaved: 'Shopify config saved',
  shopifyConfigSaveFailed: 'Failed to save Shopify config',
  shopifyConfigTestBtn: 'Test Connection',
  shopifyConfigTesting: 'Testing…',
  shopifyConfigTestOk: 'Connection successful',
  shopifyConfigTestFail: 'Connection failed',
  shopifyConfigDeleteBtn: 'Remove',
  shopifyConfigDeleting: 'Removing…',
  shopifyConfigDeleted: 'Shopify config removed',
  shopifyConfigDeleteFailed: 'Failed to remove Shopify config',
  shopifyConfigCancel: 'Cancel',
  shopifyConfigSaveBtn: 'Save',
  shopifyConfigSaving: 'Saving…',
} as const;

type TKey = keyof typeof en;

const ja: Record<TKey, string> = {
  // App
  appTitle: 'Content Creator Studio — workspace',
  appLoading: '読み込み中…',

  // Auth
  authSubtitle: 'ログインしてワークスペースにアクセス',
  authEmail: 'メールアドレス',
  authPassword: 'パスワード',
  authPasswordPlaceholder: 'パスワードを入力',
  authLoginBtn: 'ログイン',
  authLoggingIn: 'ログイン中…',
  authErrorEmpty: 'メールアドレスとパスワードを入力してください',
  authErrorInvalid: 'メールアドレスまたはパスワードが正しくありません',

  // Titlebar
  titlebarUserMgmt: 'サブスクライバー',
  titlebarInviteUser: 'ユーザーを招待',
  titlebarAccountSettings: 'アカウント設定',
  titlebarLogout: 'ログアウト',
  titlebarWpSettings: 'WordPress設定',

  // WordPress Config
  wpConfigTitle: 'WordPress設定',
  wpConfigSubtitle: 'WordPressサイトの認証情報を設定',
  wpConfigLoading: '読み込み中…',
  wpConfigConnected: '接続済み',
  wpConfigUrl: 'WordPressサイトURL',
  wpConfigUrlHint: 'WordPressサイトのルートURL（/wp-jsonなし）',
  wpConfigUser: 'WordPressユーザー名',
  wpConfigPassword: 'アプリケーションパスワード',
  wpConfigPasswordHint: '変更しない場合は空欄',
  wpConfigPasswordPlaceholder: 'xxxx xxxx xxxx xxxx xxxx xxxx',
  wpConfigPasswordPlaceholderExisting: '現在のパスワードを維持する場合は空欄',
  wpConfigPasswordGuide: 'WP管理画面 → ユーザー → アプリケーションパスワードで生成',
  wpConfigTestBtn: '接続テスト',
  wpConfigTesting: 'テスト中…',
  wpConfigTestOk: '接続成功',
  wpConfigTestFail: '接続失敗',
  wpConfigDeleteBtn: '削除',
  wpConfigDeleting: '削除中…',
  wpConfigDeleted: 'WordPress設定を削除しました',
  wpConfigCancel: 'キャンセル',
  wpConfigSaveBtn: '保存',
  wpConfigSaving: '保存中…',
  wpConfigSaved: 'WordPress設定を保存しました',
  wpConfigErrRequired: 'サイトURLとユーザー名は必須です',
  wpConfigErrPasswordRequired: '初回設定時はアプリケーションパスワードが必須です',
  wpConfigErrSaveFailed: '設定の保存に失敗しました',
  wpConfigErrDeleteFailed: '設定の削除に失敗しました',

  // Statusbar
  statusbarSynced: '同期済',

  // Topic Creator
  topicLoading: '読み込み中…',
  topicBreadcrumb: 'トピッククリエーター',
  topicAiFlowTitle: 'AI キーワード生成フロー',
  topicStep1Title: '悩みの抽出',
  topicStep1Desc: '検索ワードから「言語化されていない悩み」を抽出',
  topicStep2Title: '独自KW選定',
  topicStep2Desc: 'ブログのアイデンティティに沿った独自キーワードを選定',
  topicStep3Title: 'タイトル生成',
  topicStep3Desc: 'クリックを誘発する魅力的な記事タイトルを作成',
  topicSelectKeyword: '左のサイドバーからキーワードを選択してください',
  topicSelectHint: 'Top レベル → キーワードを展開 → 設定を編集 → AI生成',
  topicNewProject: '新しいプロジェクト',
  topicNewKeyword: '新しいキーワード',

  // Stats cards
  statsTotal: '合計',
  statsKwDone: 'KW完了',
  statsPersonaDone: 'ペルソナ完了',
  statsStructDone: '構成完了',

  // Flow Steps
  flowStep01: 'STEP 01',
  flowStep01Label: 'キーワード生成',
  flowStep02: 'STEP 02',
  flowStep02Label: 'ペルソナ・構成',
  flowStep03: 'STEP 03',
  flowStep03Label: 'ファクトチェック',
  flowAll: 'ALL',
  flowAllLabel: 'すべて表示',

  // Toast messages
  toastTopicLoadFailed: 'トピックの読み込みに失敗しました',
  toastTopicCreated: 'トピックを作成しました',
  toastTopicCreateFailed: 'トピックの作成に失敗しました',
  toastRenameFailed: '名前の変更に失敗しました',
  toastTopicDeleteConfirm: 'このトピックを削除しますか？',
  toastTopicDeleted: 'トピックを削除しました',
  toastDeleteFailed: '削除に失敗しました',
  toastKwAdded: 'キーワードを追加しました',
  toastKwAddFailed: 'キーワードの追加に失敗しました',
  toastUpdateFailed: '更新に失敗しました',
  toastResultDeleted: '削除しました',
  toastGenerateFailed: '生成に失敗しました',
  toastPersonaGenerating: 'ペルソナ・構成を生成中…',
  toastPersonaDone: 'ペルソナ・構成を生成しました',
  toastPersonaFailed: 'ペルソナ生成に失敗しました',
  toastFactCheckRunning: 'ファクトチェック実行中…',
  toastFactCheckDone: 'ファクトチェック完了',
  toastFactCheckFailed: 'ファクトチェックに失敗しました',
  toastSkipped: 'スキップしました',
  toastRestored: '復元しました',
  toastSkipFailed: 'スキップに失敗しました',
  toastRestoreFailed: '復元に失敗しました',
  toastFieldRegenDone: 'フィールドを再生成しました',
  toastFieldRegenFailed: 'フィールドの再生成に失敗しました',
  toastArticleGenerating: '記事を生成中…',
  toastArticleDone: '記事を生成しました',
  toastArticleFailed: '記事生成に失敗しました',
  toastSectionRegenDone: 'セクションを再生成しました',
  toastImageGenDone: '画像を生成しました',
  toastImageGenFailed: '画像生成に失敗しました',
  toastPublishDone: '公開しました',
  toastPublishFailed: '公開に失敗しました',

  // Topic Tree
  treeHeader: '📋 トピック設定',
  treeCollapseAll: 'すべて折りたたむ',
  treeAddTop: 'トップを追加',
  treeEdit: '編集',
  treeDelete: '削除',
  treeWpConfig: 'WordPress設定',
  treeAddKeyword: 'キーワードを追加...',

  // Keyword Card
  kwKeyword: 'キーワード',
  kwGoal: 'コンテンツのゴール',
  kwGoalPlaceholder: '例: 読者に○○を理解させ行動を促す',
  kwAudience: 'ターゲットオーディエンス',
  kwGenerating: '生成中...',
  kwGenerate: 'AI でキーワード＆タイトルを生成',
  kwViewResults: '結果を表示',

  // Results Table
  resultsEmpty: 'まだキーワードが生成されていません',
  resultsEmptyHint: 'サイドバーの「AI でキーワード＆タイトルを生成」をクリック',
  resultsSearch: '検索...',
  resultsAll: 'すべて',
  resultsColKeyword: 'キーワード',
  resultsColTitle: 'タイトル',
  resultsColStatus: 'ステータス',
  resultsColAction: 'アクション',
  resultsColDemographic: 'デモグラフィック',
  resultsColPersona1: 'ペルソナ1',
  resultsColPersona2: 'ペルソナ2',
  resultsColPersona3: 'ペルソナ3',
  resultsColDemoSize1: 'デモグラ予想サイズ①',
  resultsColDemoSize2: 'デモグラ予想サイズ②',
  resultsColDemoSize3: 'デモグラ予想サイズ③',
  resultsColFactCheck: 'ファクトチェック',
  resultsColTargetDecision: 'デモグラ決定理由',
  resultsColStructIntro: 'イントロ',
  resultsColStructNayami: '悩み',
  resultsColStructP1: 'ポイント1',
  resultsColStructP2: 'ポイント2',
  resultsColStructP3: 'ポイント3',
  resultsColStructCommon: 'よくある誤解',
  resultsColStructCta: 'CTA',
  resultsColStructMatome: 'まとめ',
  resultsColStructH2: 'H2キーワード',
  resultsEdit: '編集',
  resultsDelete: '削除',

  // Gate buttons
  gatePending: '生成待ち',
  gateNextStep: '▶ 次に進む',
  gateSkipTitle: '✕ このタイトルはNG',
  gateGenerating: '⏳ AI生成中…',
  gateFactCheck: '🔍 ファクトチェックする',
  gateSkipDemoSize: '✕ この想定人数は不要',
  gateRunningFC: '⏳ FC実行中…',
  gateDone: '✓ 完了',
  gatePublished: '🌐 公開済',
  gateRestore: '↩ 前に戻す',

  // Status labels
  statusDraft: '下書き',
  statusReady: '準備完了',
  statusKwDone: 'KW完了',
  statusPersonaWip: 'ペルソナ生成中',
  statusPersonaDone: 'ペルソナ完了',
  statusStructWip: 'FC実行中',
  statusStructDone: '構成完了',
  statusPublished: '公開済',
  statusSkipped: 'スキップ',
  // Keep old keys for backward compatibility
  statusProgress: '進行中',
  statusDone: '完了',

  // Detail Panel
  detailPanelAll: 'すべて',
  detailPanelPersona: 'ペルソナ',
  detailPanelStructure: '構成',
  detailPanelComment: 'コメント',
  detailPersonaSection: 'ペルソナ・デモグラフィック',
  detailStructSection: '記事構成',
  detailFactCheckSection: 'ファクトチェック結果',
  detailGeneratePersonaBtn: '✨ ペルソナ・構成を生成する',
  detailGeneratePersonaHint: 'ペルソナデータがありません。クリックして生成してください。',
  detailSaveBtn: '保存',
  detailCancelBtn: 'キャンセル',
  detailRegenBtn: '🔄',
  detailCommentPlaceholder: 'コメントや指示を追加…',
  detailRegenWithComment: '指示付きで再生成',
  detailTargetField: 'ターゲットフィールド',

  // Bulk Actions
  bulkSelected: '件選択中',
  bulkNextStep: '次のステップへ進む',
  bulkChangeStatus: 'ステータス変更',
  bulkGeneratePersona: 'ペルソナ・構成一括生成',
  bulkFactCheck: 'ファクトチェック一括実行',
  bulkDelete: '一括削除',

  // Article Creator
  articleCreatorBreadcrumb: '記事クリエーター',
  articleStepA: 'STEP A',
  articleStepALabel: '記事作成',
  articleStepB: 'STEP B',
  articleStepBLabel: '画像生成',
  articleStepC: 'STEP C',
  articleStepCLabel: 'アップロード',
  articleSidebarHeader: '記事一覧',
  articleNoItems: 'STRUCT_DONEのアイテムがありません',
  articleNoItemsHint: 'トピッククリエーターでSTEP 03を完了してください',
  articleReferenceBtn: 'ペルソナ・構成を参照',
  articleGenerateBtn: '記事を生成する',
  articleGenerating: '記事を生成中…',
  articlePreviewBtn: 'プレビュー',
  articleNextToImages: '記事OK → 画像生成へ',
  articleBackToEdit: '← 記事に戻る',
  articleNextToUpload: '画像OK → アップロードへ',
  articleBackToImages: '← 画像に戻る',
  articlePublishBtn: '投稿する',
  articlePublished: '🎉 公開しました！',
  articlePublishedMsg: 'この記事は正常に公開されました',

  // Section Card
  sectionRegenBtn: 'このセクションを再生成',
  sectionRegenWithInstruction: '指示付き再生成',
  sectionInstructionPlaceholder: '再生成の指示を入力…',
  sectionHeadingRegenBtn: 'タイトル再生成',
  sectionHeadingClickToEdit: 'クリックして編集',
  toastHeadingRegenDone: 'タイトルを再生成しました',

  // Image Card
  imageTastePhoto: '📷 写実的',
  imageTasteTextOverlay: '🤍 文字入り',
  imageTasteInfographic: '📊 インフォグラフィック',
  imageTasteIllustration: '🎨 イラスト',
  imageTasteCinematic: '🎬 シネマティック',
  imageEnableBtn: '有効',
  imageDisableBtn: '無効',
  imageGenBtn: '画像を生成',
  imageRegenBtn: '再生成',
  imagePromptLabel: 'プロンプト',
  imagePromptReset: 'リセット',
  imageGenAll: '全画像を生成',
  imageGenAllBtn: '全ての有効な画像を生成する',

  // Upload Panel
  uploadTabPreview: 'プレビュー',
  uploadTabSeo: 'SEO・メタ情報',
  uploadTabPlatform: '投稿設定',
  uploadSlugLabel: 'スラッグ (URL)',
  uploadExcerptLabel: '抜粋',
  uploadExcerptChars: '文字',
  uploadTagsLabel: 'タグ',
  uploadCategoryLabel: 'カテゴリ',
  uploadPlatformWordPress: 'WordPress',
  uploadPlatformShopify: 'Shopify',
  uploadStatusPublish: '公開',
  uploadStatusDraft: '下書き',
  uploadStatusSchedule: '予約投稿',
  uploadScheduleDate: '公開予定日時',
  uploadChecklist: '公開前チェックリスト',
  uploadCheck1: '記事の校正が完了している',
  uploadCheck2: '画像がすべて生成されている',
  uploadCheck3: 'SEO情報が入力されている',
  uploadCheck4: 'プラットフォームが選択されている',
  uploadPublishBtn: '投稿する',
  uploadStatsSection: 'セクション数',
  uploadStatsChars: '総文字数',
  uploadStatsImagesGen: '生成済み画像',
  uploadStatsImagesEnabled: '有効な画像',

  // Reference Modal
  refModalTitle: 'ペルソナ・構成 参照',
  refTabPersona: 'ペルソナ',
  refTabStructure: '構成',
  refTabDemographics: 'デモグラ',
  refClose: '閉じる',

  // User Modal
  usersTitle: 'サブスクライバー',
  usersAddUser: 'サブスクライバーを追加',
  usersName: '名前',
  usersNamePlaceholder: '山田 太郎',
  usersEmail: 'メールアドレス',
  usersPassword: 'パスワード',
  usersPasswordPlaceholder: '8文字以上',
  usersRole: '権限',
  usersAdd: '追加',
  usersLoading: '読み込み中…',
  usersColUser: 'サブスクライバー',
  usersColRole: '権限',
  usersColStatus: 'ステータス',
  usersColLastLogin: '最終ログイン',
  usersYou: '(自分)',
  usersActive: '有効',
  usersInactive: '無効',
  usersClickRole: 'クリックで権限を変更',
  usersDeactivate: '無効化',
  usersActivate: '有効化',
  usersDeleteBtn: '削除',

  // Role labels
  roleAdmin: '管理者',
  roleEditor: '編集者',
  roleViewer: '閲覧者',

  // User toast messages
  toastUsersLoadFailed: 'サブスクライバーの読み込みに失敗しました',
  toastUsersFillAll: 'すべてのフィールドを入力してください',
  toastUsersCreateFailed: 'サブスクライバーの作成に失敗しました',
  toastUsersUpdateFailed: '更新に失敗しました',
  toastUsersRoleChangeFailed: '権限の変更に失敗しました',
  toastUsersDeleteFailed: '削除に失敗しました',

  // Settings Modal
  settingsTitle: '設定',
  settingsSubtitle: 'パスワード・APIキー設定',
  settingsLoading: '読み込み中…',
  settingsPassword: 'パスワード',
  settingsCurrentPassword: '現在のパスワード',
  settingsNewPassword: '新しいパスワード',
  settingsConfirmPassword: 'パスワード確認',
  settingsChangePassword: 'パスワードを変更',
  settingsPasswordRequired: '現在のパスワードと新しいパスワードを入力してください',
  settingsPasswordMismatch: 'パスワードが一致しません',
  settingsPasswordTooShort: 'パスワードは6文字以上にしてください',
  settingsPasswordChanged: 'パスワードを変更しました',
  settingsPasswordFailed: 'パスワードの変更に失敗しました',
  settingsSaving: '保存中…',
  settingsDeleting: '削除中…',
  settingsKeyConfigured: '設定済み',
  settingsKeyUpdateHint: '変更しない場合は空欄',
  settingsKeyEncryptedHint: 'APIキーは暗号化して安全に保存されます',
  settingsKeyRequired: 'APIキーを入力してください',
  settingsSaveKey: 'キーを保存',
  settingsKeySaved: 'APIキーを保存しました',
  settingsKeySaveFailed: 'APIキーの保存に失敗しました',
  settingsRemoveKey: 'キーを削除',
  settingsKeyDeleted: 'APIキーを削除しました',
  settingsKeyDeleteFailed: 'APIキーの削除に失敗しました',

  // Video Script
  vsSidebarHeader: '動画スクリプト',
  vsExistingScripts: '生成済みスクリプト',
  vsAvailableArticles: '利用可能な記事',
  vsNoArticles: 'スクリプト生成可能な記事がありません',
  vsSelectArticle: '記事を選択して動画スクリプトを生成',
  vsNewScript: '新規動画スクリプト',
  vsReadyToGenerate: '「生成」をクリックしてこの記事から動画スクリプトを作成',
  vsClickGenerate: '「生成」をクリックして動画スクリプトを作成',
  vsGenerate: 'スクリプト生成',
  vsRegenerate: '再生成',
  vsGenerating: 'スクリプト生成中…',
  vsGenerated: '動画スクリプトを生成しました！',
  vsGenFailed: '動画スクリプトの生成に失敗しました',
  vsDelete: '削除',
  vsDeleted: '動画スクリプトを削除しました',
  vsDeleteFailed: '動画スクリプトの削除に失敗しました',
  vsSections: 'セクション',
  vsCreated: '作成日',
  vsHeading: '見出し',
  vsNarration: 'ナレーション',
  vsPoints: 'キーポイント',
  vsBgKeyword: '背景キーワード',
  vsSave: '保存',
  vsCancel: 'キャンセル',
  vsSectionSaved: 'セクションを更新しました',
  vsSectionSaveFailed: 'セクションの更新に失敗しました',
  vsLoadFailed: '動画スクリプトの読み込みに失敗しました',
  vsVisualType: 'ビジュアルタイプ',
  vsVisualNote: '演出メモ',
  vsEditVisual: 'ビジュアルコンテンツを編集',
  vsImagePrompt: '画像プロンプト',
  vsImagePromptPlaceholder: '生成したい画像を説明してください…',
  vsImageGenerate: '画像生成',
  vsImageRegenerate: '再生成',
  vsImageGenerating: '画像生成中…',
  vsImageGenerated: '画像が生成されました',
  vsImageGenFailed: '画像生成に失敗しました',
  vsImagePromptRequired: '画像プロンプトを入力してください',
  vsCurrentImage: '現在の画像',

  // TTS
  ttsAudioTitle: 'TTS音声',
  ttsGenerate: '音声生成',
  ttsRegenerate: '音声再生成',
  ttsGenerating: '音声生成中…',
  ttsGenerated: '音声を生成しました！',
  ttsGenFailed: '音声生成に失敗しました',
  ttsDictBtn: '読み替え辞書',
  ttsDictTitle: '読み替え辞書',
  ttsDictDesc: '漢字→読みの置換を追加して、TTSの発音を正しくします。',
  ttsDictKanji: '漢字・単語',
  ttsDictReading: '読み',
  ttsDictAdd: '追加',
  ttsDictEmpty: '辞書エントリがありません',
  ttsDictLoadFailed: '辞書の読み込みに失敗しました',
  ttsDictAddFailed: 'エントリの追加に失敗しました',
  ttsDictDeleteFailed: 'エントリの削除に失敗しました',

  // HeyGen
  heygenTitle: 'HeyGenアバター動画',
  heygenGenerate: '動画生成',
  heygenRegenerate: '動画再生成',
  heygenGenerating: '生成中…',
  heygenStarted: 'HeyGen動画生成を開始しました！',
  heygenFailed: 'HeyGen動画生成に失敗しました',
  heygenCheckStatus: 'ステータス確認',
  heygenDone: 'HeyGen動画が完成しました！',
  heygenStillProcessing: 'まだ処理中です…後で再確認してください',
  heygenCheckFailed: 'ステータス確認に失敗しました',
  heygenNeedsTts: 'まずTTS音声を生成してください（ステップ1）',

  // Remotion
  remotionTitle: 'Remotion字幕合成',
  remotionGenerate: 'レンダリング開始',
  remotionRegenerate: '再レンダリング',
  remotionGenerating: 'レンダリング開始中…',
  remotionStarted: 'Remotionレンダリングを開始しました！',
  remotionFailed: 'Remotionレンダリングに失敗しました',
  remotionCheckStatus: 'ステータス確認',
  remotionDone: '最終動画が完成しました！',
  remotionStillProcessing: 'まだレンダリング中…後で再確認してください',
  remotionCheckFailed: 'ステータス確認に失敗しました',
  remotionDownload: '最終動画をダウンロード',
  remotionNeedsHeygen: 'まずHeyGen動画を生成してください（ステップ2）',

  // Settings
  vsSettings: '動画設定',
  vsOrientation: '向き',
  vsAvatar: 'アバター',
  vsLoadAvatars: 'アバター読込',
  vsNoAvatars: 'HeyGenアカウントにアバターがありません',
  vsTheme: 'テーマ',
  avatarLoadFailed: 'アバターの読み込みに失敗しました',
  settingsSaveFailed: '設定の保存に失敗しました',

  // Shopify Config
  treeShopifyConfig: 'Shopify設定',
  shopifyConfigTitle: 'Shopify設定',
  shopifyConfigConnected: '接続済み',
  shopifyConfigDomain: 'ショップドメイン',
  shopifyConfigDomainHint: '例: your-store.myshopify.com',
  shopifyConfigToken: 'アクセストークン',
  shopifyConfigTokenHint: '変更しない場合は空欄',
  shopifyConfigTokenPlaceholder: 'shpat_xxxxxxxxxxxxx',
  shopifyConfigTokenPlaceholderExisting: '変更しない場合は空欄のまま',
  shopifyConfigBlogId: 'ブログID（任意）',
  shopifyConfigBlogIdHint: '空欄の場合はデフォルトブログを使用',
  shopifyConfigErrDomain: 'ショップドメインは必須です',
  shopifyConfigErrToken: '初回設定にはアクセストークンが必要です',
  shopifyConfigSaved: 'Shopify設定を保存しました',
  shopifyConfigSaveFailed: 'Shopify設定の保存に失敗しました',
  shopifyConfigTestBtn: '接続テスト',
  shopifyConfigTesting: 'テスト中…',
  shopifyConfigTestOk: '接続成功',
  shopifyConfigTestFail: '接続失敗',
  shopifyConfigDeleteBtn: '削除',
  shopifyConfigDeleting: '削除中…',
  shopifyConfigDeleted: 'Shopify設定を削除しました',
  shopifyConfigDeleteFailed: 'Shopify設定の削除に失敗しました',
  shopifyConfigCancel: 'キャンセル',
  shopifyConfigSaveBtn: '保存',
  shopifyConfigSaving: '保存中…',
};

const translations: Record<Lang, Record<TKey, string>> = { en, ja };

interface LanguageContextValue {
  lang: Lang;
  toggle: () => void;
  t: (key: TKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ja');

  function toggle() {
    setLang((l) => (l === 'en' ? 'ja' : 'en'));
  }

  function t(key: TKey): string {
    return translations[lang][key];
  }

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
