import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Lang = 'en' | 'ja';

const en = {
  // App
  appTitle: 'Content Creator Studio — workspace',
  appLoading: 'Loading…',

  // Auth
  authSubtitle: 'Login to access your workspace',
  authEmail: 'Email',
  authPassword: 'Password',
  authPasswordPlaceholder: 'Enter password',
  authLoginBtn: 'Login',
  authLoggingIn: 'Logging in…',
  authErrorEmpty: 'Please enter your email and password',
  authErrorInvalid: 'Incorrect email or password',

  // Titlebar
  titlebarUserMgmt: 'Subscribers',
  titlebarInviteUser: 'Invite User',
  titlebarAccountSettings: 'Account Settings',
  titlebarLogout: 'Logout',
  titlebarWpSettings: 'WordPress Settings',

  // WordPress Config
  wpConfigTitle: 'WordPress Settings',
  wpConfigSubtitle: 'Configure your WordPress site credentials',
  wpConfigLoading: 'Loading…',
  wpConfigConnected: 'Connected',
  wpConfigUrl: 'WordPress Site URL',
  wpConfigUrlHint: 'Your WordPress site root URL (without /wp-json)',
  wpConfigUser: 'WordPress Username',
  wpConfigPassword: 'Application Password',
  wpConfigPasswordHint: 'leave blank to keep current',
  wpConfigPasswordPlaceholder: 'xxxx xxxx xxxx xxxx xxxx xxxx',
  wpConfigPasswordPlaceholderExisting: 'Leave blank to keep current password',
  wpConfigPasswordGuide: 'Generate at WP Admin → Users → Application Passwords',
  wpConfigTestBtn: 'Test Connection',
  wpConfigTesting: 'Testing…',
  wpConfigTestOk: 'Connection successful',
  wpConfigTestFail: 'Connection failed',
  wpConfigDeleteBtn: 'Remove',
  wpConfigDeleting: 'Removing…',
  wpConfigDeleted: 'WordPress config removed',
  wpConfigCancel: 'Cancel',
  wpConfigSaveBtn: 'Save',
  wpConfigSaving: 'Saving…',
  wpConfigSaved: 'WordPress settings saved',
  wpConfigErrRequired: 'Site URL and username are required',
  wpConfigErrPasswordRequired: 'Application password is required for first setup',
  wpConfigErrSaveFailed: 'Failed to save settings',
  wpConfigErrDeleteFailed: 'Failed to remove settings',

  // Statusbar
  statusbarSynced: 'Synced',

  // Topic Creator
  topicLoading: 'Loading…',
  topicBreadcrumb: 'Topic Creator',
  topicAiFlowTitle: 'AI Keyword Generation Flow',
  topicStep1Title: 'Extracting worries',
  topicStep1Desc: 'Extracting "unverbalized worries" from search terms',
  topicStep2Title: 'Original KW selection',
  topicStep2Desc: "Select unique keywords that match your blog's identity",
  topicStep3Title: 'Title Generation',
  topicStep3Desc: 'Create compelling article titles that will attract clicks',
  topicSelectKeyword: 'Select a keyword from the left sidebar',
  topicSelectHint: 'Top Level → Expand Keyword → Edit Settings → Generate AI',
  topicNewProject: 'New Project',
  topicNewKeyword: 'New keyword',

  // Stats cards
  statsTotal: 'Total',
  statsKwDone: 'KW Done',
  statsPersonaDone: 'Persona Done',
  statsStructDone: 'Struct Done',

  // Flow Steps
  flowStep01: 'STEP 01',
  flowStep01Label: 'Keyword Generation',
  flowStep02: 'STEP 02',
  flowStep02Label: 'Persona & Structure',
  flowStep03: 'STEP 03',
  flowStep03Label: 'Fact Check',
  flowAll: 'ALL',
  flowAllLabel: 'Show All',

  // Toast messages
  toastTopicLoadFailed: 'Failed to load topics',
  toastTopicCreated: 'Topic created',
  toastTopicCreateFailed: 'Failed to create topic',
  toastRenameFailed: 'Failed to rename',
  toastTopicDeleteConfirm: 'Delete this topic?',
  toastTopicDeleted: 'Topic deleted',
  toastDeleteFailed: 'Failed to delete',
  toastKwAdded: 'Keyword added',
  toastKwAddFailed: 'Failed to add keyword',
  toastUpdateFailed: 'Failed to update',
  toastResultDeleted: 'Deleted',
  toastGenerateFailed: 'Failed to generate',
  toastPersonaGenerating: 'Generating persona & structure…',
  toastPersonaDone: 'Persona & structure generated',
  toastPersonaFailed: 'Persona generation failed',
  toastFactCheckRunning: 'Running fact check…',
  toastFactCheckDone: 'Fact check complete',
  toastFactCheckFailed: 'Fact check failed',
  toastSkipped: 'Skipped',
  toastRestored: 'Restored',
  toastSkipFailed: 'Failed to skip',
  toastRestoreFailed: 'Failed to restore',
  toastFieldRegenDone: 'Field regenerated',
  toastFieldRegenFailed: 'Failed to regenerate field',
  toastArticleGenerating: 'Generating article…',
  toastArticleDone: 'Article generated',
  toastArticleFailed: 'Article generation failed',
  toastSectionRegenDone: 'Section regenerated',
  toastImageGenDone: 'Image generated',
  toastImageGenFailed: 'Image generation failed',
  toastPublishDone: 'Published successfully',
  toastPublishFailed: 'Publish failed',

  // Topic Tree
  treeHeader: '📋 Topic Settings',
  treeCollapseAll: 'Collapse all',
  treeAddTop: 'Add top level',
  treeEdit: 'Edit',
  treeDelete: 'Delete',
  treeWpConfig: 'WordPress Settings',
  treeAddKeyword: 'Add Keywords...',

  // Keyword Card
  kwKeyword: 'Keyword',
  kwGoal: 'Content Goal',
  kwGoalPlaceholder: 'e.g. Help readers understand X and take action',
  kwAudience: 'Target Audience',
  kwGenerating: 'Generating...',
  kwGenerate: 'AI-powered keyword and title generation',
  kwViewResults: 'Showing results',

  // Results Table
  resultsEmpty: 'No keywords generated yet',
  resultsEmptyHint: 'Click "AI-powered keyword and title generation" in the sidebar',
  resultsSearch: 'search...',
  resultsAll: 'all',
  resultsColKeyword: 'Keyword',
  resultsColTitle: 'Title',
  resultsColStatus: 'Status',
  resultsColAction: 'Action',
  resultsColDemographic: 'Demographic',
  resultsColPersona1: 'Persona 1',
  resultsColPersona2: 'Persona 2',
  resultsColPersona3: 'Persona 3',
  resultsColDemoSize1: 'Est. Demo Size ①',
  resultsColDemoSize2: 'Est. Demo Size ②',
  resultsColDemoSize3: 'Est. Demo Size ③',
  resultsColFactCheck: 'Fact Check',
  resultsColTargetDecision: 'Demo Decision Reason',
  resultsColStructIntro: 'Intro',
  resultsColStructNayami: 'Problem',
  resultsColStructP1: 'Point 1',
  resultsColStructP2: 'Point 2',
  resultsColStructP3: 'Point 3',
  resultsColStructCommon: 'Common',
  resultsColStructCta: 'CTA',
  resultsColStructMatome: 'Summary',
  resultsColStructH2: 'H2 Keys',
  resultsEdit: 'Edit',
  resultsDelete: 'Delete',

  // Gate buttons
  gatePending: 'Pending',
  gateNextStep: '▶ Next Step',
  gateSkipTitle: '✕ Skip this title',
  gateGenerating: '⏳ Generating…',
  gateFactCheck: '🔍 Run Fact Check',
  gateSkipDemoSize: '✕ Skip demo size',
  gateRunningFC: '⏳ Running FC…',
  gateDone: '✓ Done',
  gatePublished: '🌐 Published',
  gateRestore: '↩ Restore',

  // Status labels
  statusDraft: 'draft',
  statusReady: 'ready',
  statusKwDone: 'kw done',
  statusPersonaWip: 'persona…',
  statusPersonaDone: 'persona ok',
  statusStructWip: 'checking…',
  statusStructDone: 'struct ok',
  statusPublished: 'published',
  statusSkipped: 'skipped',
  // Keep old keys for backward compatibility
  statusProgress: 'in progress',
  statusDone: 'completion',

  // Detail Panel
  detailPanelAll: 'All',
  detailPanelPersona: 'Persona',
  detailPanelStructure: 'Structure',
  detailPanelComment: 'Comment',
  detailPersonaSection: 'Persona & Demographics',
  detailStructSection: 'Article Structure',
  detailFactCheckSection: 'Fact Check Results',
  detailGeneratePersonaBtn: '✨ Generate Persona & Structure',
  detailGeneratePersonaHint: 'No persona data yet. Click to generate.',
  detailSaveBtn: 'Save',
  detailCancelBtn: 'Cancel',
  detailRegenBtn: '🔄',
  detailCommentPlaceholder: 'Add a comment or instruction…',
  detailRegenWithComment: 'Regenerate with instruction',
  detailTargetField: 'Target field',
  detailSelectField: '-- Select a field --',
  detailFieldTitle: 'Title',
  detailFieldDemographic: 'Demographic',
  detailFieldPersona1: 'Persona 1',
  detailFieldPersona2: 'Persona 2',
  detailFieldPersona3: 'Persona 3',
  detailFieldDemoSize1: 'Demo Size Estimate 1',
  detailFieldDemoSize2: 'Demo Size Estimate 2',
  detailFieldDemoSize3: 'Demo Size Estimate 3',
  detailFieldStructIntro: 'Intro',
  detailFieldStructNayami: 'Problem',
  detailFieldStructP1: 'Point 1',
  detailFieldStructP2: 'Point 2',
  detailFieldStructP3: 'Point 3',
  detailFieldStructCommon: 'Common Misconceptions',
  detailFieldStructCta: 'CTA',
  detailFieldStructMatome: 'Summary',
  detailFieldStructH2: 'H2 Keywords',
  detailRegenSuccess: 'Regenerated successfully',
  detailRegenFailed: 'Regeneration failed',
  detailTitleUpdated: 'Title updated',
  detailTitleUpdateFailed: 'Title update failed',
  detailTitleRegenSuccess: 'Title regenerated',
  detailTitleRegenFailed: 'Title regeneration failed',
  detailSaveBtnLabel: 'Save',
  detailCancelBtnLabel: 'Cancel',
  detailClickToEdit: 'Click to edit',
  detailEditTitle: 'Edit title',
  detailRegenTitle: 'Regenerate title',
  detailGenerating: 'Generating…',
  detailRegenerating: 'Regenerating…',
  detailFactConfirmed: '✓ Confirmed',
  detailFactIncorrect: '✗ Incorrect',
  detailFactUncertain: '? Uncertain',
  detailFactCheckLabel: 'Fact Check',
  detailTargetDecision: 'Target Decision',
  detailDemoSize: 'Demo Size',
  detailFactVerified: '✓ Verified',
  detailFactNeedsReview: '? Needs Review',

  // User Settings Modal (Account)
  acctSettingsTitle: 'Account Settings',
  acctProfileSection: 'Profile',
  acctNameLabel: 'Name',
  acctEmailLabel: 'Email',
  acctPasswordSection: 'Change Password',
  acctCurrentPasswordPlaceholder: 'Enter only if changing',
  acctNewPasswordPlaceholder: '6 characters or more',
  acctConfirmPlaceholder: 'Enter again',
  acctConfirmPasswordLabel: 'Confirm New Password',
  acctNoChanges: 'No changes',
  acctSaved: 'Settings saved',
  acctSaveFailed: 'Failed to save',

  // Article Tree status labels
  articleStatusReady: 'Not started',
  articleStatusWriting: 'Writing',
  articleStatusArticleDone: 'Article OK',
  articleStatusImaging: 'Generating images',
  articleStatusImageDone: 'Images OK',
  articleStatusUploaded: 'Uploaded',
  articleRefHint: 'View persona & structure',

  // Video Script statuses
  vsStatusPending: 'Not generated',
  vsStatusGenerating: 'Generating…',
  vsStatusPreparing: 'Preparing…',
  vsStatusProcessing: 'Processing…',
  vsStatusRendering: 'Rendering…',
  vsStatusDone: 'Generated',
  vsStatusCompleted: 'Completed',
  vsStatusFailed: 'Failed',

  // Image Card
  imageDefaultPhoto: 'Realistic photo of a person reading content on laptop, modern office, natural light',
  imageDefaultTextOverlay: 'Clean minimalist background for Japanese text overlay',
  imageDefaultInfographic: 'Flat design infographic layout with icons and data visualization elements',
  imageDefaultIllustration: 'Colorful digital illustration related to the article topic',
  imageDefaultCinematic: 'Cinematic wide shot with dramatic lighting and shallow depth of field',
  imageHistoryTitle: 'Previous images',
  imageHistorySelect: 'Select',
  imageSelected: 'Image selected',
  imageSelectFailed: 'Failed to select image',
  imageNotGenerated: 'Not generated',
  imageLabel: 'Image',
  sectionTypeIntro: 'Intro',
  sectionTypeNayami: 'Problem',
  sectionTypePoint: 'Point',
  sectionTypeCommon: 'Misconceptions',
  sectionTypeCta: 'CTA',
  sectionTypeMatome: 'Summary',

  // Bulk Actions
  bulkSelected: 'selected',
  bulkNextStep: 'Next Step',
  bulkChangeStatus: 'Change Status',
  bulkGeneratePersona: 'Generate Persona & Structure',
  bulkFactCheck: 'Run Fact Check',
  bulkDelete: 'Delete',

  // Article Creator
  articleCreatorBreadcrumb: 'Article Creator',
  articleStepA: 'STEP A',
  articleStepALabel: 'Write Article',
  articleStepB: 'STEP B',
  articleStepBLabel: 'Generate Images',
  articleStepC: 'STEP C',
  articleStepCLabel: 'Upload',
  articleSidebarHeader: 'Articles',
  articleFilterALL: 'All',
  articleFilterNO_ARTICLE: 'Not started',
  articleFilterWRITING: 'Writing',
  articleFilterARTICLE_DONE: 'Article done',
  articleFilterIMAGE_DONE: 'Image done',
  articleFilterUPLOADED: 'Published',
  articleNoItems: 'No STRUCT_DONE items yet',
  articleNoItemsHint: 'Complete STEP 03 in Topic Creator first',
  articleReferenceBtn: 'Refer to Persona and Structure',
  articleGenerateBtn: 'Generate Article',
  articleGenerating: 'Generating article…',
  articlePreviewBtn: 'Preview',
  articleNextToImages: 'Article OK → Proceed to images',
  articleBackToEdit: '← Back to article',
  articleNextToUpload: 'Images OK → Proceed to upload',
  articleBackToImages: '← Back to images',
  articlePublishBtn: 'Publish',
  articlePublished: 'Published successfully!',
  articlePublishedMsg: 'This article has been published successfully',

  // Section Card
  sectionRegenBtn: 'Regenerate this section',
  sectionRegenWithInstruction: 'Directed regeneration',
  sectionInstructionPlaceholder: 'Enter regeneration instructions…',
  sectionHeadingRegenBtn: 'Regenerate heading',
  sectionHeadingClickToEdit: 'Click to edit',
  sectionExpandBtn: 'Expand',
  sectionCollapseBtn: 'Collapse',
  sectionContentLabel: 'Content',
  sectionSaveBtn: 'Save',
  sectionSaved: 'Saved',
  sectionUnsaved: 'Unsaved changes',
  sectionSaving: 'Saving…',
  toastHeadingRegenDone: 'Heading regenerated',
  toastTitleRegenDone: 'Title regenerated',
  toastTitleRegenFailed: 'Title regeneration failed',
  titleRegenBtn: 'Regenerate title',
  titleRegenTooltip: 'Generate a new title using AI',

  // Image Card
  imageTastePhoto: 'Photo',
  imageTasteTextOverlay: 'Text Overlay',
  imageTasteInfographic: 'Infographic',
  imageTasteIllustration: 'Illustration',
  imageTasteCinematic: 'Cinematic',
  imageEnableBtn: 'Enable',
  imageDisableBtn: 'Disable',
  imageGenBtn: 'Generate Image',
  imageRegenBtn: 'Regenerate',
  imagePromptLabel: 'Prompt',
  imagePromptReset: 'Reset',
  imageGenAll: 'Generate All Images',
  imageGenAllBtn: 'Generate all enabled images',
  imageBulkGenBtn: 'Bulk Generate Images',
  imageBulkGenTooltip: 'Generates images for all enabled slots at once.\n\n• To SKIP an image: click the "Disable" button on its card before bulk generating.\n• To RE-ENABLE: click "Enable" on the card.\n• Only green-highlighted (enabled) cards will be generated.\n• Each image uses its own prompt — edit prompts individually on each card.',
  imageMasterPromptLabel: 'Master Prompt (auto-applies to all images)',
  imageMasterPromptPlaceholder: 'Type a prompt here — it will be applied to every image box automatically.',
  imageMasterPromptApply: 'Apply to all',
  imageTextInsideBtn: 'Text inside',
  imageTextOutsideBtn: 'Text outside',
  imageTextPositionTooltip: 'Toggle whether the title text appears inside or outside the image',
  imageOverlayTitleLabel: 'Overlay Title',
  imageOverlayTitlePlaceholder: 'Text displayed on the image...',
  imageOverlayTitleRegen: 'Regen',
  imageOverlayTitleRegenTooltip: 'Generate a new overlay title with AI',
  toastOverlayTitleDone: 'Overlay title regenerated',
  toastOverlayTitleFailed: 'Failed to regenerate overlay title',
  imageVariationAdd: '+ Add new option',
  imageVariationNamePrompt: 'Variation name?',
  imageVariationPromptPrompt: 'Prompt text for this variation?',

  // Upload Panel
  uploadTabPreview: 'Preview',
  uploadTabSeo: 'SEO & Meta',
  uploadTabPlatform: 'Post Settings',
  uploadSlugLabel: 'Slug (URL)',
  uploadExcerptLabel: 'Excerpt',
  uploadExcerptChars: 'chars',
  uploadTagsLabel: 'Tags',
  uploadCategoryLabel: 'Category',
  uploadPlatformWordPress: 'WordPress',
  uploadPlatformShopify: 'Shopify',
  uploadStatusPublish: 'Publish',
  uploadStatusDraft: 'Draft',
  uploadStatusSchedule: 'Schedule',
  uploadScheduleDate: 'Scheduled date',
  uploadChecklist: 'Pre-publish checklist',
  uploadCheck1: 'Article has been proofread',
  uploadCheck2: 'All images have been generated',
  uploadCheck3: 'SEO information is filled in',
  uploadCheck4: 'Platform has been selected',
  uploadPublishBtn: 'Publish',
  uploadFixThumbBtn: 'Fix Thumbnail',
  uploadFixAllBtn: 'Fix All Thumbnails',
  uploadFixThumbHint: 'Already published? Update the WordPress thumbnail from the first image.',
  uploadFixThumbDone: 'Thumbnail updated on WordPress',
  uploadFixAllDone: 'Thumbnails updated',
  uploadFixThumbFailed: 'Failed to update thumbnail',
  uploadStatsSection: 'Sections',
  uploadStatsChars: 'Total characters',
  uploadStatsImagesGen: 'Generated images',
  uploadStatsImagesEnabled: '有効な画像',

  // Reference Modal
  refModalTitle: 'ペルソナ・構成 参照',
  refTabPersona: 'ペルソナ',
  refTabStructure: '構成',
  refTabDemographics: 'デモグラ',
  refClose: '閉じる',

  // User Modal
  usersTitle: 'SUbscribers',
  usersAddUser: 'Add User',
  usersName: 'Name',
  usersNamePlaceholder: 'John Smith',
  usersEmail: 'Email',
  usersPassword: 'Password',
  usersPasswordPlaceholder: '8+ characters',
  usersRole: 'Role',
  usersAdd: 'Add',
  usersLoading: 'Loading…',
  usersColUser: 'User',
  usersColRole: 'Role',
  usersColStatus: 'Status',
  usersColLastLogin: 'Last Login',
  usersYou: '(You)',
  usersActive: 'Active',
  usersInactive: 'Inactive',
  usersClickRole: 'Click to change role',
  usersDeactivate: 'Deactivate',
  usersActivate: 'Activate',
  usersDeleteBtn: 'Delete',

  // Role labels
  roleAdmin: 'Admin',
  roleEditor: 'Editor',
  roleViewer: 'Viewer',

  // User toast messages
  toastUsersLoadFailed: 'Failed to load users',
  toastUsersFillAll: 'Please fill in all fields',
  toastUsersCreateFailed: 'Failed to create user',
  toastUsersUpdateFailed: 'Failed to update',
  toastUsersRoleChangeFailed: 'Failed to change role',
  toastUsersDeleteFailed: 'Failed to delete',

  // Settings Modal
  settingsTitle: 'Settings',
  settingsSubtitle: 'Password & API key configuration',
  settingsLoading: 'Loading…',
  settingsPassword: 'Password',
  settingsCurrentPassword: 'Current Password',
  settingsNewPassword: 'New Password',
  settingsConfirmPassword: 'Confirm Password',
  settingsChangePassword: 'Change Password',
  settingsPasswordRequired: 'Current and new password are required',
  settingsPasswordMismatch: 'Passwords do not match',
  settingsPasswordTooShort: 'Password must be at least 6 characters',
  settingsPasswordChanged: 'Password changed successfully',
  settingsPasswordFailed: 'Failed to change password',
  settingsSaving: 'Saving…',
  settingsDeleting: 'Removing…',
  settingsKeyConfigured: 'Configured',
  settingsKeyUpdateHint: 'leave blank to keep current',
  settingsKeyEncryptedHint: 'Your key is encrypted and stored securely',
  settingsKeyRequired: 'Please enter an API key',
  settingsSaveKey: 'Save Key',
  settingsKeySaved: 'API key saved',
  settingsKeySaveFailed: 'Failed to save API key',
  settingsRemoveKey: 'Remove Key',
  settingsKeyDeleted: 'API key removed',
  settingsKeyDeleteFailed: 'Failed to remove API key',

  // Video Script
  vsSidebarHeader: 'Video Scripts',
  vsExistingScripts: 'Generated Scripts',
  vsAvailableArticles: 'Available Articles',
  vsNoArticles: 'No articles available for script generation',
  vsSelectArticle: 'Select an article to generate a video script',
  vsNewScript: 'New Video Script',
  vsReadyToGenerate: 'Click Generate to create a video script from this article',
  vsClickGenerate: 'Click "Generate" to create a video script',
  vsGenerate: 'Generate Script',
  vsRegenerate: 'Regenerate',
  vsGenerating: 'Generating script…',
  vsGenerated: 'Video script generated!',
  vsGenFailed: 'Failed to generate video script',
  vsDelete: 'Delete',
  vsDeleted: 'Video script deleted',
  vsDeleteFailed: 'Failed to delete video script',
  vsSections: 'sections',
  vsCreated: 'Created',
  vsHeading: 'Heading',
  vsNarration: 'Narration',
  vsPoints: 'Key Points',
  vsBgKeyword: 'BG Keyword',
  vsSave: 'Save',
  vsCancel: 'Cancel',
  vsSectionSaved: 'Section updated',
  vsSectionSaveFailed: 'Failed to update section',
  vsLoadFailed: 'Failed to load video scripts',
  vsVisualType: 'Visual Type',
  vsVisualNote: 'Visual Note',
  vsEditVisual: 'Edit Visual Content',
  vsImagePrompt: 'Image Prompt',
  vsImagePromptPlaceholder: 'Describe the image you want to generate…',
  vsImageGenerate: 'Generate Image',
  vsImageRegenerate: 'Regenerate',
  vsImageGenerating: 'Generating image…',
  vsImageGenerated: 'Image generated',
  vsImageGenFailed: 'Image generation failed',
  vsImagePromptRequired: 'Please enter an image prompt',
  vsCurrentImage: 'Current Image',

  // TTS
  ttsAudioTitle: 'TTS Audio',
  ttsGenerate: 'Generate Audio',
  ttsRegenerate: 'Regenerate Audio',
  ttsGenerating: 'Generating audio…',
  ttsGenerated: 'Audio generated!',
  ttsGenFailed: 'Failed to generate audio',
  ttsOrRecord: 'or record / upload your own audio:',
  ttsUploadAudio: 'Upload Audio',
  ttsUploading: 'Uploading…',
  ttsUploadDone: 'Custom audio uploaded!',
  ttsUploadFailed: 'Failed to upload audio',
  ttsCustomLabel: 'Custom audio active',
  voiceRecorderStart: 'Record',
  voiceRecorderStop: 'Stop',
  ttsDictBtn: 'Reading Dictionary',
  ttsDictTitle: 'Reading Dictionary (読み替え辞書)',
  ttsDictDesc: 'Add kanji → reading replacements so TTS pronounces words correctly.',
  ttsDictKanji: 'Kanji / Word',
  ttsDictReading: 'Reading',
  ttsDictAdd: 'Add',
  ttsDictEmpty: 'No dictionary entries yet',
  ttsDictLoadFailed: 'Failed to load dictionary',
  ttsDictAddFailed: 'Failed to add entry',
  ttsDictDeleteFailed: 'Failed to delete entry',

  // HeyGen
  heygenTitle: 'HeyGen Avatar Video',
  heygenGenerate: 'Generate Video',
  heygenRegenerate: 'Regenerate Video',
  heygenGenerating: 'Generating…',
  heygenStarted: 'HeyGen video generation started!',
  heygenFailed: 'HeyGen video generation failed',
  heygenCheckStatus: 'Check Status',
  heygenDone: 'HeyGen video ready!',
  heygenStillProcessing: 'Still processing… check again later',
  heygenCheckFailed: 'Failed to check status',
  heygenNeedsTts: 'Generate TTS audio first (Step 1)',

  // Remotion
  remotionTitle: 'Remotion Subtitle Rendering',
  remotionGenerate: 'Start Rendering',
  remotionRegenerate: 'Re-render',
  remotionGenerating: 'Starting render…',
  remotionStarted: 'Remotion rendering started!',
  remotionFailed: 'Remotion rendering failed',
  remotionCheckStatus: 'Check Status',
  remotionDone: 'Final video ready!',
  remotionStillProcessing: 'Still rendering… check again later',
  remotionCheckFailed: 'Failed to check status',
  remotionDownload: 'Download Final Video',
  remotionNeedsHeygen: 'Generate HeyGen video first (Step 2)',

  // Settings
  vsSettings: 'Video Settings',
  vsOrientation: 'Orientation',
  vsAvatar: 'Avatar',
  vsLoadAvatars: 'Load Avatars',
  vsNoAvatars: 'No avatars found in your HeyGen account',
  vsVoice: 'Voice',
  vsTheme: 'Theme',
  vsPattern: 'Pattern',
  vsPatternFormalDesc: 'Funeral, legal, finance, medical, traditional',
  vsPatternCasualDesc: 'Entertainment, beauty, lifestyle (coming soon)',
  vsPatternMinimalDesc: 'Education, how-to, explainer (coming soon)',
  vsPatternCorporateDesc: 'B2B, company profile, IR (coming soon)',
  previewBuildBtn: 'Build Preview',
  previewBuilding: 'Fetching backgrounds…',
  previewBuildDone: 'Preview backgrounds ready',
  previewBuildFailed: 'Failed to build preview',
  previewBuildForceConfirm: 'Overwrite existing per-section images? (Cancel = keep existing, only fill empty ones)',
  previewBuildHint: 'Pre-fill section backgrounds from Pexels (Japan-aware keywords) so you can review before rendering.',
  previewBuildAiBtn: 'AI Backgrounds',
  previewBuildAiHint: 'Generate section backgrounds with AI instead of free stock photos.',

  // Background Picker
  bgPickerTitle: 'Choose Background',
  bgPickerSearchPlaceholder: 'Search free images & videos…',
  bgPickerSearchBtn: 'Search',
  bgPickerSearching: 'Searching…',
  bgPickerSearchFailed: 'Search failed',
  bgPickerAll: 'All',
  bgPickerPhotos: 'Photos',
  bgPickerVideos: 'Videos',
  bgPickerEmpty: 'No results found',
  bgPickerEmptyHint: 'Try a different keyword or use AI generation below.',
  bgPickerSelected: 'Background set',
  bgPickerSelectFailed: 'Failed to set background',
  bgPickerSelecting: 'Setting…',
  bgPickerAiSection: 'Or generate with AI',
  bgPickerAiPlaceholder: 'Describe the background you want…',
  bgPickerAiBtn: 'AI Generate',
  bgPickerAiGenerating: 'Generating…',
  bgPickerAiDone: 'AI background generated',
  bgPickerAiFailed: 'AI generation failed',
  bgPickerChange: 'Change',
  avatarLoadFailed: 'Failed to load avatars',
  settingsSaveFailed: 'Failed to save settings',

  // Campaign Defaults
  treeCampaignDefaults: 'Campaign Defaults',
  campaignDefaultsTitle: 'Campaign Defaults',
  campaignDefaultsImageTaste: 'Default Image Style',
  campaignDefaultsVideoBg: 'Video Background Source',
  campaignDefaultsTaste_PHOTO: 'Photo',
  campaignDefaultsTaste_TEXT_OVERLAY: 'Text Overlay',
  campaignDefaultsTaste_INFOGRAPHIC: 'Infographic',
  campaignDefaultsTaste_ILLUSTRATION: 'Illustration',
  campaignDefaultsTaste_CINEMATIC: 'Cinematic',
  campaignDefaultsBg_free: 'Free Stock (Pexels)',
  campaignDefaultsBg_free_desc: 'Use free stock photos from Pexels as default backgrounds. Replace individual sections with AI if needed.',
  campaignDefaultsBg_ai: 'AI Generated',
  campaignDefaultsBg_ai_desc: 'Generate backgrounds with AI (Kie.ai) for all sections. Requires Kie API key.',
  campaignDefaultsSaveBtn: 'Save Defaults',
  campaignDefaultsSaved: 'Campaign defaults saved',
  campaignDefaultsSaveFailed: 'Failed to save campaign defaults',

  // Shopify Config
  treeShopifyConfig: 'Shopify Settings',
  shopifyConfigTitle: 'Shopify Settings',
  shopifyConfigConnected: 'Connected',
  shopifyConfigDomain: 'Shop Domain',
  shopifyConfigDomainHint: 'e.g. your-store.myshopify.com',
  shopifyConfigToken: 'Access Token',
  shopifyConfigTokenHint: 'leave blank to keep current',
  shopifyConfigTokenPlaceholder: 'shpat_xxxxxxxxxxxxx',
  shopifyConfigTokenPlaceholderExisting: 'Leave blank to keep current token',
  shopifyConfigBlogId: 'Blog ID (optional)',
  shopifyConfigBlogIdHint: 'Leave empty to use default blog',
  shopifyConfigErrDomain: 'Shop domain is required',
  shopifyConfigErrToken: 'Access token is required for first setup',
  shopifyConfigSaved: 'Shopify config saved',
  shopifyConfigSaveFailed: 'Failed to save Shopify config',
  shopifyConfigTestBtn: 'Test Connection',
  shopifyConfigTesting: 'Testing…',
  shopifyConfigTestOk: 'Connection successful',
  shopifyConfigTestFail: 'Connection failed',
  shopifyConfigDeleteBtn: 'Remove',
  shopifyConfigDeleting: 'Removing…',
  shopifyConfigDeleted: 'Shopify config removed',
  shopifyConfigDeleteFailed: 'Failed to remove Shopify config',
  shopifyConfigCancel: 'Cancel',
  shopifyConfigSaveBtn: 'Save',
  shopifyConfigSaving: 'Saving…',

  // HeyGen Avatars
  heygenAvatarPageTitle: 'HeyGen Avatars',
  heygenAvatarCreateTitle: 'Create a new HeyGen avatar',
  heygenAvatarCreateBtn: 'New Avatar',
  heygenAvatarCreating: 'Creating…',
  heygenAvatarTypeLabel: 'Avatar Type',
  heygenAvatarTypePhoto: 'Photo',
  heygenAvatarTypeVideo: 'Video',
  heygenAvatarFieldName: 'Avatar name',
  heygenAvatarFieldNamePlaceholder: 'e.g. Yamada Taro',
  heygenAvatarFieldFile: 'Avatar File',
  heygenAvatarFieldImageUrl: 'Photo URL',
  heygenAvatarFieldImageUrlHint: 'Public URL to a clear front-facing photo (JPG/PNG/WebP).',
  heygenAvatarFieldImage: 'Avatar Photo',
  heygenAvatarDropzone: 'Click or drag & drop an image here',
  heygenAvatarDropzoneHint: 'JPG, PNG, WebP — max 10 MB',
  heygenAvatarDropzonePhoto: 'Click or drag & drop a photo here',
  heygenAvatarDropzoneVideo: 'Click or drag & drop a video here',
  heygenAvatarDropzoneHintPhoto: 'JPG, PNG — max 10 MB',
  heygenAvatarDropzoneHintVideo: 'MP4, MOV, WebM — max 50 MB',
  heygenAvatarErrorNotImage: 'Please select an image file',
  heygenAvatarErrorNotVideo: 'Please select a video file',
  heygenAvatarErrorTooLarge: 'Image must be under 10 MB',
  heygenAvatarErrorVideoTooLarge: 'Video must be under 50 MB',
  heygenAvatarErrorNoImage: 'Please upload a photo',
  heygenAvatarErrorNoFile: 'Please upload a file',
  heygenAvatarCreateNote: 'The avatar will be uploaded to HeyGen and registered immediately. Photo avatars can be used as talking photos for video generation.',
  heygenAvatarCancel: 'Cancel',
  heygenAvatarCreatedToast: 'Avatar created successfully',
  heygenAvatarCreateFailed: 'Failed to create avatar',
  heygenAvatarErrorEmpty: 'Name is required',
  heygenAvatarLoadFailed: 'Failed to load avatars',
  heygenAvatarEmptyTitle: 'No avatars yet',
  heygenAvatarEmptyHint: 'Click "New Avatar" to create your first custom HeyGen avatar.',
  heygenAvatarRefresh: 'Refresh',
  heygenAvatarDelete: 'Delete',
  heygenAvatarDeleteConfirm: 'Delete this avatar?',
  heygenAvatarDeletedToast: 'Avatar deleted',
  heygenAvatarDeleteFailed: 'Failed to delete avatar',
  heygenAvatarRefreshFailed: 'Failed to refresh avatar',
  heygenAvatarReadyToast: 'Avatar is ready',
  heygenAvatarStatusPENDING: 'Queued',
  heygenAvatarStatusUPLOADING: 'Uploading',
  heygenAvatarStatusTRAINING: 'Training',
  heygenAvatarStatusREADY: 'Ready',
  heygenAvatarStatusFAILED: 'Failed',
  heygenAvatarRetry: 'Retry',
  heygenAvatarRetryStarted: 'Retrying avatar creation…',
  heygenAvatarRetryFailed: 'Failed to retry avatar',
  heygenAvatarApiMissingTitle: 'HeyGen API Key Required',
  heygenAvatarApiMissingDesc: 'Please configure your HeyGen API key in Settings before creating an avatar.',
  heygenAvatarOpenSettings: 'Open Settings',
  voicePreviewFailed: 'Failed to preview voice',
  vsVoiceMale: 'Male',
  vsVoiceFemale: 'Female',
} as const;

type TKey = keyof typeof en;

const ja: Record<TKey, string> = {
  // App
  appTitle: 'Content Creator Studio — workspace',
  appLoading: '読み込み中…',

  // Auth
  authSubtitle: 'ログインしてワークスペースにアクセス',
  authEmail: 'メールアドレス',
  authPassword: 'パスワード',
  authPasswordPlaceholder: 'パスワードを入力',
  authLoginBtn: 'ログイン',
  authLoggingIn: 'ログイン中…',
  authErrorEmpty: 'メールアドレスとパスワードを入力してください',
  authErrorInvalid: 'メールアドレスまたはパスワードが正しくありません',

  // Titlebar
  titlebarUserMgmt: 'サブスクライバー',
  titlebarInviteUser: 'ユーザーを招待',
  titlebarAccountSettings: 'アカウント設定',
  titlebarLogout: 'ログアウト',
  titlebarWpSettings: 'WordPress設定',

  // WordPress Config
  wpConfigTitle: 'WordPress設定',
  wpConfigSubtitle: 'WordPressサイトの認証情報を設定',
  wpConfigLoading: '読み込み中…',
  wpConfigConnected: '接続済み',
  wpConfigUrl: 'WordPressサイトURL',
  wpConfigUrlHint: 'WordPressサイトのルートURL（/wp-jsonなし）',
  wpConfigUser: 'WordPressユーザー名',
  wpConfigPassword: 'アプリケーションパスワード',
  wpConfigPasswordHint: '変更しない場合は空欄',
  wpConfigPasswordPlaceholder: 'xxxx xxxx xxxx xxxx xxxx xxxx',
  wpConfigPasswordPlaceholderExisting: '現在のパスワードを維持する場合は空欄',
  wpConfigPasswordGuide: 'WP管理画面 → ユーザー → アプリケーションパスワードで生成',
  wpConfigTestBtn: '接続テスト',
  wpConfigTesting: 'テスト中…',
  wpConfigTestOk: '接続成功',
  wpConfigTestFail: '接続失敗',
  wpConfigDeleteBtn: '削除',
  wpConfigDeleting: '削除中…',
  wpConfigDeleted: 'WordPress設定を削除しました',
  wpConfigCancel: 'キャンセル',
  wpConfigSaveBtn: '保存',
  wpConfigSaving: '保存中…',
  wpConfigSaved: 'WordPress設定を保存しました',
  wpConfigErrRequired: 'サイトURLとユーザー名は必須です',
  wpConfigErrPasswordRequired: '初回設定時はアプリケーションパスワードが必須です',
  wpConfigErrSaveFailed: '設定の保存に失敗しました',
  wpConfigErrDeleteFailed: '設定の削除に失敗しました',

  // Statusbar
  statusbarSynced: '同期済',

  // Topic Creator
  topicLoading: '読み込み中…',
  topicBreadcrumb: 'トピッククリエーター',
  topicAiFlowTitle: 'AI キーワード生成フロー',
  topicStep1Title: '悩みの抽出',
  topicStep1Desc: '検索ワードから「言語化されていない悩み」を抽出',
  topicStep2Title: '独自KW選定',
  topicStep2Desc: 'ブログのアイデンティティに沿った独自キーワードを選定',
  topicStep3Title: 'タイトル生成',
  topicStep3Desc: 'クリックを誘発する魅力的な記事タイトルを作成',
  topicSelectKeyword: '左のサイドバーからキーワードを選択してください',
  topicSelectHint: 'Top レベル → キーワードを展開 → 設定を編集 → AI生成',
  topicNewProject: '新しいプロジェクト',
  topicNewKeyword: '新しいキーワード',

  // Stats cards
  statsTotal: '合計',
  statsKwDone: 'KW完了',
  statsPersonaDone: 'ペルソナ完了',
  statsStructDone: '構成完了',

  // Flow Steps
  flowStep01: 'STEP 01',
  flowStep01Label: 'キーワード生成',
  flowStep02: 'STEP 02',
  flowStep02Label: 'ペルソナ・構成',
  flowStep03: 'STEP 03',
  flowStep03Label: 'ファクトチェック',
  flowAll: 'ALL',
  flowAllLabel: 'すべて表示',

  // Toast messages
  toastTopicLoadFailed: 'トピックの読み込みに失敗しました',
  toastTopicCreated: 'トピックを作成しました',
  toastTopicCreateFailed: 'トピックの作成に失敗しました',
  toastRenameFailed: '名前の変更に失敗しました',
  toastTopicDeleteConfirm: 'このトピックを削除しますか？',
  toastTopicDeleted: 'トピックを削除しました',
  toastDeleteFailed: '削除に失敗しました',
  toastKwAdded: 'キーワードを追加しました',
  toastKwAddFailed: 'キーワードの追加に失敗しました',
  toastUpdateFailed: '更新に失敗しました',
  toastResultDeleted: '削除しました',
  toastGenerateFailed: '生成に失敗しました',
  toastPersonaGenerating: 'ペルソナ・構成を生成中…',
  toastPersonaDone: 'ペルソナ・構成を生成しました',
  toastPersonaFailed: 'ペルソナ生成に失敗しました',
  toastFactCheckRunning: 'ファクトチェック実行中…',
  toastFactCheckDone: 'ファクトチェック完了',
  toastFactCheckFailed: 'ファクトチェックに失敗しました',
  toastSkipped: 'スキップしました',
  toastRestored: '復元しました',
  toastSkipFailed: 'スキップに失敗しました',
  toastRestoreFailed: '復元に失敗しました',
  toastFieldRegenDone: 'フィールドを再生成しました',
  toastFieldRegenFailed: 'フィールドの再生成に失敗しました',
  toastArticleGenerating: '記事を生成中…',
  toastArticleDone: '記事を生成しました',
  toastArticleFailed: '記事生成に失敗しました',
  toastSectionRegenDone: 'セクションを再生成しました',
  toastImageGenDone: '画像を生成しました',
  toastImageGenFailed: '画像生成に失敗しました',
  toastPublishDone: '公開しました',
  toastPublishFailed: '公開に失敗しました',

  // Topic Tree
  treeHeader: '📋 トピック設定',
  treeCollapseAll: 'すべて折りたたむ',
  treeAddTop: 'トップを追加',
  treeEdit: '編集',
  treeDelete: '削除',
  treeWpConfig: 'WordPress設定',
  treeAddKeyword: 'キーワードを追加...',

  // Keyword Card
  kwKeyword: 'キーワード',
  kwGoal: 'コンテンツのゴール',
  kwGoalPlaceholder: '例: 読者に○○を理解させ行動を促す',
  kwAudience: 'ターゲットオーディエンス',
  kwGenerating: '生成中...',
  kwGenerate: 'AI でキーワード＆タイトルを生成',
  kwViewResults: '結果を表示',

  // Results Table
  resultsEmpty: 'まだキーワードが生成されていません',
  resultsEmptyHint: 'サイドバーの「AI でキーワード＆タイトルを生成」をクリック',
  resultsSearch: '検索...',
  resultsAll: 'すべて',
  resultsColKeyword: 'キーワード',
  resultsColTitle: 'タイトル',
  resultsColStatus: 'ステータス',
  resultsColAction: 'アクション',
  resultsColDemographic: 'デモグラフィック',
  resultsColPersona1: 'ペルソナ1',
  resultsColPersona2: 'ペルソナ2',
  resultsColPersona3: 'ペルソナ3',
  resultsColDemoSize1: 'デモグラ予想サイズ①',
  resultsColDemoSize2: 'デモグラ予想サイズ②',
  resultsColDemoSize3: 'デモグラ予想サイズ③',
  resultsColFactCheck: 'ファクトチェック',
  resultsColTargetDecision: 'デモグラ決定理由',
  resultsColStructIntro: 'イントロ',
  resultsColStructNayami: '悩み',
  resultsColStructP1: 'ポイント1',
  resultsColStructP2: 'ポイント2',
  resultsColStructP3: 'ポイント3',
  resultsColStructCommon: 'よくある誤解',
  resultsColStructCta: 'CTA',
  resultsColStructMatome: 'まとめ',
  resultsColStructH2: 'H2キーワード',
  resultsEdit: '編集',
  resultsDelete: '削除',

  // Gate buttons
  gatePending: '生成待ち',
  gateNextStep: '▶ 次に進む',
  gateSkipTitle: '✕ このタイトルはNG',
  gateGenerating: '⏳ AI生成中…',
  gateFactCheck: '🔍 ファクトチェックする',
  gateSkipDemoSize: '✕ この想定人数は不要',
  gateRunningFC: '⏳ FC実行中…',
  gateDone: '✓ 完了',
  gatePublished: '🌐 公開済',
  gateRestore: '↩ 前に戻す',

  // Status labels
  statusDraft: '下書き',
  statusReady: '準備完了',
  statusKwDone: 'KW完了',
  statusPersonaWip: 'ペルソナ生成中',
  statusPersonaDone: 'ペルソナ完了',
  statusStructWip: 'FC実行中',
  statusStructDone: '構成完了',
  statusPublished: '公開済',
  statusSkipped: 'スキップ',
  // Keep old keys for backward compatibility
  statusProgress: '進行中',
  statusDone: '完了',

  // Detail Panel
  detailPanelAll: 'すべて',
  detailPanelPersona: 'ペルソナ',
  detailPanelStructure: '構成',
  detailPanelComment: 'コメント',
  detailPersonaSection: 'ペルソナ・デモグラフィック',
  detailStructSection: '記事構成',
  detailFactCheckSection: 'ファクトチェック結果',
  detailGeneratePersonaBtn: '✨ ペルソナ・構成を生成する',
  detailGeneratePersonaHint: 'ペルソナデータがありません。クリックして生成してください。',
  detailSaveBtn: '保存',
  detailCancelBtn: 'キャンセル',
  detailRegenBtn: '🔄',
  detailCommentPlaceholder: 'コメントや指示を追加…',
  detailRegenWithComment: '指示付きで再生成',
  detailTargetField: 'ターゲットフィールド',
  detailSelectField: '-- フィールドを選択 --',
  detailFieldTitle: 'タイトル',
  detailFieldDemographic: 'デモグラフィック',
  detailFieldPersona1: 'ペルソナ1',
  detailFieldPersona2: 'ペルソナ2',
  detailFieldPersona3: 'ペルソナ3',
  detailFieldDemoSize1: 'デモグラ予想サイズ①',
  detailFieldDemoSize2: 'デモグラ予想サイズ②',
  detailFieldDemoSize3: 'デモグラ予想サイズ③',
  detailFieldStructIntro: 'イントロ',
  detailFieldStructNayami: '悩み',
  detailFieldStructP1: 'ポイント1',
  detailFieldStructP2: 'ポイント2',
  detailFieldStructP3: 'ポイント3',
  detailFieldStructCommon: 'よくある誤解',
  detailFieldStructCta: 'CTA',
  detailFieldStructMatome: 'まとめ',
  detailFieldStructH2: 'H2キーワード',
  detailRegenSuccess: '再生成しました',
  detailRegenFailed: '再生成に失敗しました',
  detailTitleUpdated: 'タイトルを更新しました',
  detailTitleUpdateFailed: 'タイトル更新に失敗しました',
  detailTitleRegenSuccess: 'タイトルを再生成しました',
  detailTitleRegenFailed: 'タイトル再生成に失敗しました',
  detailSaveBtnLabel: '保存',
  detailCancelBtnLabel: 'キャンセル',
  detailClickToEdit: 'クリックして編集',
  detailEditTitle: 'タイトルを編集',
  detailRegenTitle: 'タイトルを再生成',
  detailGenerating: '生成中…',
  detailRegenerating: '再生成中…',
  detailFactConfirmed: '✓ 確認済み',
  detailFactIncorrect: '✗ 不正確',
  detailFactUncertain: '? 不確実',
  detailFactCheckLabel: 'ファクトチェック',
  detailTargetDecision: 'ターゲット判定',
  detailDemoSize: 'デモサイズ',
  detailFactVerified: '✓ 確認済',
  detailFactNeedsReview: '? 要確認',

  // User Settings Modal (Account)
  acctSettingsTitle: 'アカウント設定',
  acctProfileSection: 'プロフィール',
  acctNameLabel: '名前',
  acctEmailLabel: 'メールアドレス',
  acctPasswordSection: 'パスワード変更',
  acctCurrentPasswordPlaceholder: '変更する場合のみ入力',
  acctNewPasswordPlaceholder: '6文字以上',
  acctConfirmPlaceholder: 'もう一度入力',
  acctConfirmPasswordLabel: '新しいパスワード（確認）',
  acctNoChanges: '変更がありません',
  acctSaved: '設定を保存しました',
  acctSaveFailed: '保存に失敗しました',

  // Article Tree status labels
  articleStatusReady: '未作成',
  articleStatusWriting: '作成中',
  articleStatusArticleDone: '記事OK',
  articleStatusImaging: '画像生成中',
  articleStatusImageDone: '画像OK',
  articleStatusUploaded: 'アップ済',
  articleRefHint: 'ペルソナ・構成を参照',

  // Video Script statuses
  vsStatusPending: '未生成',
  vsStatusGenerating: '生成中…',
  vsStatusPreparing: '準備中…',
  vsStatusProcessing: '処理中…',
  vsStatusRendering: 'レンダリング中…',
  vsStatusDone: '生成済',
  vsStatusCompleted: '完了',
  vsStatusFailed: '失敗',

  // Image Card
  imageDefaultPhoto: 'ノートパソコンでコンテンツを読む人物のリアルな写真、モダンなオフィス、自然光',
  imageDefaultTextOverlay: '日本語テキストオーバーレイ用のクリーンなミニマリスト背景',
  imageDefaultInfographic: 'アイコンとデータ可視化要素を含むフラットデザインのインフォグラフィックレイアウト',
  imageDefaultIllustration: '記事のトピックに関連するカラフルなデジタルイラスト',
  imageDefaultCinematic: 'ドラマチックな照明と浅い被写界深度のシネマティックなワイドショット',
  imageHistoryTitle: '過去の生成画像',
  imageHistorySelect: '選択',
  imageSelected: '画像を選択しました',
  imageSelectFailed: '画像の選択に失敗しました',
  imageNotGenerated: '未生成',
  imageLabel: '画像',
  sectionTypeIntro: 'イントロ',
  sectionTypeNayami: '悩み',
  sectionTypePoint: 'ポイント',
  sectionTypeCommon: '誤解',
  sectionTypeCta: 'CTA',
  sectionTypeMatome: 'まとめ',

  // Bulk Actions
  bulkSelected: '件選択中',
  bulkNextStep: '次のステップへ進む',
  bulkChangeStatus: 'ステータス変更',
  bulkGeneratePersona: 'ペルソナ・構成一括生成',
  bulkFactCheck: 'ファクトチェック一括実行',
  bulkDelete: '一括削除',

  // Article Creator
  articleCreatorBreadcrumb: '記事クリエーター',
  articleStepA: 'STEP A',
  articleStepALabel: '記事作成',
  articleStepB: 'STEP B',
  articleStepBLabel: '画像生成',
  articleStepC: 'STEP C',
  articleStepCLabel: 'アップロード',
  articleSidebarHeader: '記事一覧',
  articleFilterALL: 'すべて',
  articleFilterNO_ARTICLE: '未作成',
  articleFilterWRITING: '作成中',
  articleFilterARTICLE_DONE: '記事OK',
  articleFilterIMAGE_DONE: '画像OK',
  articleFilterUPLOADED: '公開済',
  articleNoItems: 'STRUCT_DONEのアイテムがありません',
  articleNoItemsHint: 'トピッククリエーターでSTEP 03を完了してください',
  articleReferenceBtn: 'ペルソナ・構成を参照',
  articleGenerateBtn: '記事を生成する',
  articleGenerating: '記事を生成中…',
  articlePreviewBtn: 'プレビュー',
  articleNextToImages: '記事OK → 画像生成へ',
  articleBackToEdit: '← 記事に戻る',
  articleNextToUpload: '画像OK → アップロードへ',
  articleBackToImages: '← 画像に戻る',
  articlePublishBtn: '投稿する',
  articlePublished: '🎉 公開しました！',
  articlePublishedMsg: 'この記事は正常に公開されました',

  // Section Card
  sectionRegenBtn: 'このセクションを再生成',
  sectionRegenWithInstruction: '指示付き再生成',
  sectionInstructionPlaceholder: '再生成の指示を入力…',
  sectionHeadingRegenBtn: 'タイトル再生成',
  sectionHeadingClickToEdit: 'クリックして編集',
  sectionExpandBtn: '展開',
  sectionCollapseBtn: '折りたたむ',
  sectionContentLabel: '本文',
  sectionSaveBtn: '保存',
  sectionSaved: '保存済み',
  sectionUnsaved: '未保存の変更',
  sectionSaving: '保存中…',
  toastHeadingRegenDone: 'タイトルを再生成しました',
  toastTitleRegenDone: '記事タイトルを再生成しました',
  toastTitleRegenFailed: '記事タイトルの再生成に失敗しました',
  titleRegenBtn: 'タイトル再生成',
  titleRegenTooltip: 'AIで新しいタイトルを生成します',

  // Image Card
  imageTastePhoto: '📷 写実的',
  imageTasteTextOverlay: '🤍 文字入り',
  imageTasteInfographic: '📊 インフォグラフィック',
  imageTasteIllustration: '🎨 イラスト',
  imageTasteCinematic: '🎬 シネマティック',
  imageEnableBtn: '有効',
  imageDisableBtn: '無効',
  imageGenBtn: '画像を生成',
  imageRegenBtn: '再生成',
  imagePromptLabel: 'プロンプト',
  imagePromptReset: 'リセット',
  imageGenAll: '全画像を生成',
  imageGenAllBtn: '全ての有効な画像を生成する',
  imageBulkGenBtn: '一括画像生成',
  imageBulkGenTooltip: '有効なスロットの画像を一括で生成します。\n\n• スキップしたい場合：カードの「無効」ボタンをクリックしてください。\n• 再度有効にする場合：カードの「有効」ボタンをクリックしてください。\n• 緑色（有効）のカードのみ生成されます。\n• 各画像は個別のプロンプトを使用します — カードごとに編集できます。',
  imageMasterPromptLabel: 'マスタープロンプト（全画像に自動適用）',
  imageMasterPromptPlaceholder: 'ここにプロンプトを入力すると、全ての画像ボックスに自動で適用されます。',
  imageMasterPromptApply: '全てに適用',
  imageTextInsideBtn: 'テキスト内側',
  imageTextOutsideBtn: 'テキスト外側',
  imageTextPositionTooltip: 'タイトルテキストを画像の内側または外側に表示するかを切り替えます',
  imageOverlayTitleLabel: 'オーバーレイタイトル',
  imageOverlayTitlePlaceholder: '画像に表示するテキスト...',
  imageOverlayTitleRegen: '再生成',
  imageOverlayTitleRegenTooltip: 'AIで新しいオーバーレイタイトルを生成',
  toastOverlayTitleDone: 'オーバーレイタイトルを再生成しました',
  toastOverlayTitleFailed: 'オーバーレイタイトルの再生成に失敗しました',
  imageVariationAdd: '＋ 他のオプション',
  imageVariationNamePrompt: 'バリエーション名は？',
  imageVariationPromptPrompt: 'このバリエーションのプロンプトは？',

  // Upload Panel
  uploadTabPreview: 'プレビュー',
  uploadTabSeo: 'SEO・メタ情報',
  uploadTabPlatform: '投稿設定',
  uploadSlugLabel: 'スラッグ (URL)',
  uploadExcerptLabel: '抜粋',
  uploadExcerptChars: '文字',
  uploadTagsLabel: 'タグ',
  uploadCategoryLabel: 'カテゴリ',
  uploadPlatformWordPress: 'WordPress',
  uploadPlatformShopify: 'Shopify',
  uploadStatusPublish: '公開',
  uploadStatusDraft: '下書き',
  uploadStatusSchedule: '予約投稿',
  uploadScheduleDate: '公開予定日時',
  uploadChecklist: '公開前チェックリスト',
  uploadCheck1: '記事の校正が完了している',
  uploadCheck2: '画像がすべて生成されている',
  uploadCheck3: 'SEO情報が入力されている',
  uploadCheck4: 'プラットフォームが選択されている',
  uploadPublishBtn: '投稿する',
  uploadFixThumbBtn: 'サムネイル修正',
  uploadFixAllBtn: '全サムネイル修正',
  uploadFixThumbHint: '投稿済み？最初の画像からWordPressサムネイルを更新します。',
  uploadFixThumbDone: 'WordPressのサムネイルを更新しました',
  uploadFixAllDone: 'サムネイルを更新しました',
  uploadFixThumbFailed: 'サムネイルの更新に失敗しました',
  uploadStatsSection: 'セクション数',
  uploadStatsChars: '総文字数',
  uploadStatsImagesGen: '生成済み画像',
  uploadStatsImagesEnabled: '有効な画像',

  // Reference Modal
  refModalTitle: 'ペルソナ・構成 参照',
  refTabPersona: 'ペルソナ',
  refTabStructure: '構成',
  refTabDemographics: 'デモグラ',
  refClose: '閉じる',

  // User Modal
  usersTitle: 'サブスクライバー',
  usersAddUser: 'サブスクライバーを追加',
  usersName: '名前',
  usersNamePlaceholder: '山田 太郎',
  usersEmail: 'メールアドレス',
  usersPassword: 'パスワード',
  usersPasswordPlaceholder: '8文字以上',
  usersRole: '権限',
  usersAdd: '追加',
  usersLoading: '読み込み中…',
  usersColUser: 'サブスクライバー',
  usersColRole: '権限',
  usersColStatus: 'ステータス',
  usersColLastLogin: '最終ログイン',
  usersYou: '(自分)',
  usersActive: '有効',
  usersInactive: '無効',
  usersClickRole: 'クリックで権限を変更',
  usersDeactivate: '無効化',
  usersActivate: '有効化',
  usersDeleteBtn: '削除',

  // Role labels
  roleAdmin: '管理者',
  roleEditor: '編集者',
  roleViewer: '閲覧者',

  // User toast messages
  toastUsersLoadFailed: 'サブスクライバーの読み込みに失敗しました',
  toastUsersFillAll: 'すべてのフィールドを入力してください',
  toastUsersCreateFailed: 'サブスクライバーの作成に失敗しました',
  toastUsersUpdateFailed: '更新に失敗しました',
  toastUsersRoleChangeFailed: '権限の変更に失敗しました',
  toastUsersDeleteFailed: '削除に失敗しました',

  // Settings Modal
  settingsTitle: '設定',
  settingsSubtitle: 'パスワード・APIキー設定',
  settingsLoading: '読み込み中…',
  settingsPassword: 'パスワード',
  settingsCurrentPassword: '現在のパスワード',
  settingsNewPassword: '新しいパスワード',
  settingsConfirmPassword: 'パスワード確認',
  settingsChangePassword: 'パスワードを変更',
  settingsPasswordRequired: '現在のパスワードと新しいパスワードを入力してください',
  settingsPasswordMismatch: 'パスワードが一致しません',
  settingsPasswordTooShort: 'パスワードは6文字以上にしてください',
  settingsPasswordChanged: 'パスワードを変更しました',
  settingsPasswordFailed: 'パスワードの変更に失敗しました',
  settingsSaving: '保存中…',
  settingsDeleting: '削除中…',
  settingsKeyConfigured: '設定済み',
  settingsKeyUpdateHint: '変更しない場合は空欄',
  settingsKeyEncryptedHint: 'APIキーは暗号化して安全に保存されます',
  settingsKeyRequired: 'APIキーを入力してください',
  settingsSaveKey: 'キーを保存',
  settingsKeySaved: 'APIキーを保存しました',
  settingsKeySaveFailed: 'APIキーの保存に失敗しました',
  settingsRemoveKey: 'キーを削除',
  settingsKeyDeleted: 'APIキーを削除しました',
  settingsKeyDeleteFailed: 'APIキーの削除に失敗しました',

  // Video Script
  vsSidebarHeader: '動画スクリプト',
  vsExistingScripts: '生成済みスクリプト',
  vsAvailableArticles: '利用可能な記事',
  vsNoArticles: 'スクリプト生成可能な記事がありません',
  vsSelectArticle: '記事を選択して動画スクリプトを生成',
  vsNewScript: '新規動画スクリプト',
  vsReadyToGenerate: '「生成」をクリックしてこの記事から動画スクリプトを作成',
  vsClickGenerate: '「生成」をクリックして動画スクリプトを作成',
  vsGenerate: 'スクリプト生成',
  vsRegenerate: '再生成',
  vsGenerating: 'スクリプト生成中…',
  vsGenerated: '動画スクリプトを生成しました！',
  vsGenFailed: '動画スクリプトの生成に失敗しました',
  vsDelete: '削除',
  vsDeleted: '動画スクリプトを削除しました',
  vsDeleteFailed: '動画スクリプトの削除に失敗しました',
  vsSections: 'セクション',
  vsCreated: '作成日',
  vsHeading: '見出し',
  vsNarration: 'ナレーション',
  vsPoints: 'キーポイント',
  vsBgKeyword: '背景キーワード',
  vsSave: '保存',
  vsCancel: 'キャンセル',
  vsSectionSaved: 'セクションを更新しました',
  vsSectionSaveFailed: 'セクションの更新に失敗しました',
  vsLoadFailed: '動画スクリプトの読み込みに失敗しました',
  vsVisualType: 'ビジュアルタイプ',
  vsVisualNote: '演出メモ',
  vsEditVisual: 'ビジュアルコンテンツを編集',
  vsImagePrompt: '画像プロンプト',
  vsImagePromptPlaceholder: '生成したい画像を説明してください…',
  vsImageGenerate: '画像生成',
  vsImageRegenerate: '再生成',
  vsImageGenerating: '画像生成中…',
  vsImageGenerated: '画像が生成されました',
  vsImageGenFailed: '画像生成に失敗しました',
  vsImagePromptRequired: '画像プロンプトを入力してください',
  vsCurrentImage: '現在の画像',

  // TTS
  ttsAudioTitle: 'TTS音声',
  ttsGenerate: '音声生成',
  ttsRegenerate: '音声再生成',
  ttsGenerating: '音声生成中…',
  ttsGenerated: '音声を生成しました！',
  ttsGenFailed: '音声生成に失敗しました',
  ttsOrRecord: 'または自分の音声を録音・アップロード：',
  ttsUploadAudio: '音声アップロード',
  ttsUploading: 'アップロード中…',
  ttsUploadDone: 'カスタム音声をアップロードしました！',
  ttsUploadFailed: '音声アップロードに失敗しました',
  ttsCustomLabel: 'カスタム音声使用中',
  voiceRecorderStart: '録音',
  voiceRecorderStop: '停止',
  ttsDictBtn: '読み替え辞書',
  ttsDictTitle: '読み替え辞書',
  ttsDictDesc: '漢字→読みの置換を追加して、TTSの発音を正しくします。',
  ttsDictKanji: '漢字・単語',
  ttsDictReading: '読み',
  ttsDictAdd: '追加',
  ttsDictEmpty: '辞書エントリがありません',
  ttsDictLoadFailed: '辞書の読み込みに失敗しました',
  ttsDictAddFailed: 'エントリの追加に失敗しました',
  ttsDictDeleteFailed: 'エントリの削除に失敗しました',

  // HeyGen
  heygenTitle: 'HeyGenアバター動画',
  heygenGenerate: '動画生成',
  heygenRegenerate: '動画再生成',
  heygenGenerating: '生成中…',
  heygenStarted: 'HeyGen動画生成を開始しました！',
  heygenFailed: 'HeyGen動画生成に失敗しました',
  heygenCheckStatus: 'ステータス確認',
  heygenDone: 'HeyGen動画が完成しました！',
  heygenStillProcessing: 'まだ処理中です…後で再確認してください',
  heygenCheckFailed: 'ステータス確認に失敗しました',
  heygenNeedsTts: 'まずTTS音声を生成してください（ステップ1）',

  // Remotion
  remotionTitle: 'Remotion字幕合成',
  remotionGenerate: 'レンダリング開始',
  remotionRegenerate: '再レンダリング',
  remotionGenerating: 'レンダリング開始中…',
  remotionStarted: 'Remotionレンダリングを開始しました！',
  remotionFailed: 'Remotionレンダリングに失敗しました',
  remotionCheckStatus: 'ステータス確認',
  remotionDone: '最終動画が完成しました！',
  remotionStillProcessing: 'まだレンダリング中…後で再確認してください',
  remotionCheckFailed: 'ステータス確認に失敗しました',
  remotionDownload: '最終動画をダウンロード',
  remotionNeedsHeygen: 'まずHeyGen動画を生成してください（ステップ2）',

  // Settings
  vsSettings: '動画設定',
  vsOrientation: '向き',
  vsAvatar: 'アバター',
  vsLoadAvatars: 'アバター読込',
  vsNoAvatars: 'HeyGenアカウントにアバターがありません',
  vsVoice: '音声',
  vsTheme: 'テーマ',
  vsPattern: 'パターン',
  vsPatternFormalDesc: '仏事・法律・金融・医療・伝統文化',
  vsPatternCasualDesc: 'エンタメ・美容・ライフスタイル（近日公開）',
  vsPatternMinimalDesc: '教育・HowTo・解説（近日公開）',
  vsPatternCorporateDesc: 'BtoB・企業紹介・IR（近日公開）',
  previewBuildBtn: 'プレビュー作成',
  previewBuilding: '背景画像を取得中…',
  previewBuildDone: 'プレビュー背景を取得しました',
  previewBuildFailed: 'プレビュー作成に失敗しました',
  previewBuildForceConfirm: '既存のセクション画像を上書きしますか？（キャンセル＝既存を保持し、空のみ埋める）',
  previewBuildHint: 'Pexels（日本語キーワード対応）からセクション背景を事前取得し、レンダリング前に確認できます。',
  previewBuildAiBtn: 'AI背景',
  previewBuildAiHint: '無料ストック写真の代わりにAIでセクション背景を生成します。',

  // Background Picker
  bgPickerTitle: '背景を選択',
  bgPickerSearchPlaceholder: '無料画像・動画を検索…',
  bgPickerSearchBtn: '検索',
  bgPickerSearching: '検索中…',
  bgPickerSearchFailed: '検索に失敗しました',
  bgPickerAll: 'すべて',
  bgPickerPhotos: '写真',
  bgPickerVideos: '動画',
  bgPickerEmpty: '結果が見つかりません',
  bgPickerEmptyHint: '別のキーワードを試すか、下のAI生成をご利用ください。',
  bgPickerSelected: '背景を設定しました',
  bgPickerSelectFailed: '背景の設定に失敗しました',
  bgPickerSelecting: '設定中…',
  bgPickerAiSection: 'またはAIで生成',
  bgPickerAiPlaceholder: '欲しい背景を説明してください…',
  bgPickerAiBtn: 'AI生成',
  bgPickerAiGenerating: '生成中…',
  bgPickerAiDone: 'AI背景を生成しました',
  bgPickerAiFailed: 'AI生成に失敗しました',
  bgPickerChange: '変更',
  avatarLoadFailed: 'アバターの読み込みに失敗しました',
  settingsSaveFailed: '設定の保存に失敗しました',

  // Campaign Defaults
  treeCampaignDefaults: 'キャンペーン設定',
  campaignDefaultsTitle: 'キャンペーン設定',
  campaignDefaultsImageTaste: 'デフォルト画像スタイル',
  campaignDefaultsVideoBg: '動画背景ソース',
  campaignDefaultsTaste_PHOTO: '写真',
  campaignDefaultsTaste_TEXT_OVERLAY: 'テキストオーバーレイ',
  campaignDefaultsTaste_INFOGRAPHIC: 'インフォグラフィック',
  campaignDefaultsTaste_ILLUSTRATION: 'イラスト',
  campaignDefaultsTaste_CINEMATIC: 'シネマティック',
  campaignDefaultsBg_free: '無料ストック（Pexels）',
  campaignDefaultsBg_free_desc: 'Pexelsの無料ストック写真をデフォルト背景として使用。必要に応じて個別セクションをAI生成に置換可能。',
  campaignDefaultsBg_ai: 'AI生成',
  campaignDefaultsBg_ai_desc: 'AI（Kie.ai）で全セクションの背景を生成。Kie APIキーが必要です。',
  campaignDefaultsSaveBtn: '設定を保存',
  campaignDefaultsSaved: 'キャンペーン設定を保存しました',
  campaignDefaultsSaveFailed: 'キャンペーン設定の保存に失敗しました',

  // Shopify Config
  treeShopifyConfig: 'Shopify設定',
  shopifyConfigTitle: 'Shopify設定',
  shopifyConfigConnected: '接続済み',
  shopifyConfigDomain: 'ショップドメイン',
  shopifyConfigDomainHint: '例: your-store.myshopify.com',
  shopifyConfigToken: 'アクセストークン',
  shopifyConfigTokenHint: '変更しない場合は空欄',
  shopifyConfigTokenPlaceholder: 'shpat_xxxxxxxxxxxxx',
  shopifyConfigTokenPlaceholderExisting: '変更しない場合は空欄のまま',
  shopifyConfigBlogId: 'ブログID（任意）',
  shopifyConfigBlogIdHint: '空欄の場合はデフォルトブログを使用',
  shopifyConfigErrDomain: 'ショップドメインは必須です',
  shopifyConfigErrToken: '初回設定にはアクセストークンが必要です',
  shopifyConfigSaved: 'Shopify設定を保存しました',
  shopifyConfigSaveFailed: 'Shopify設定の保存に失敗しました',
  shopifyConfigTestBtn: '接続テスト',
  shopifyConfigTesting: 'テスト中…',
  shopifyConfigTestOk: '接続成功',
  shopifyConfigTestFail: '接続失敗',
  shopifyConfigDeleteBtn: '削除',
  shopifyConfigDeleting: '削除中…',
  shopifyConfigDeleted: 'Shopify設定を削除しました',
  shopifyConfigDeleteFailed: 'Shopify設定の削除に失敗しました',
  shopifyConfigCancel: 'キャンセル',
  shopifyConfigSaveBtn: '保存',
  shopifyConfigSaving: '保存中…',

  // HeyGen Avatars
  heygenAvatarPageTitle: 'HeyGenアバター',
  heygenAvatarCreateTitle: '新しいHeyGenアバターを作成',
  heygenAvatarCreateBtn: '新規アバター',
  heygenAvatarCreating: '作成中…',
  heygenAvatarTypeLabel: 'アバタータイプ',
  heygenAvatarTypePhoto: '写真',
  heygenAvatarTypeVideo: '動画',
  heygenAvatarFieldName: 'アバター名',
  heygenAvatarFieldNamePlaceholder: '例：山田太郎',
  heygenAvatarFieldFile: 'アバターファイル',
  heygenAvatarFieldImageUrl: '写真URL',
  heygenAvatarFieldImageUrlHint: '正面向きの鮮明な写真の公開URL（JPG/PNG/WebP）',
  heygenAvatarFieldImage: 'アバター写真',
  heygenAvatarDropzone: 'クリックまたはドラッグ＆ドロップで画像をアップロード',
  heygenAvatarDropzoneHint: 'JPG、PNG、WebP — 最大10MB',
  heygenAvatarDropzonePhoto: 'クリックまたはドラッグ＆ドロップで写真をアップロード',
  heygenAvatarDropzoneVideo: 'クリックまたはドラッグ＆ドロップで動画をアップロード',
  heygenAvatarDropzoneHintPhoto: 'JPG、PNG — 最大10MB',
  heygenAvatarDropzoneHintVideo: 'MP4、MOV、WebM — 最大50MB',
  heygenAvatarErrorNotImage: '画像ファイルを選択してください',
  heygenAvatarErrorNotVideo: '動画ファイルを選択してください',
  heygenAvatarErrorTooLarge: '画像は10MB以下にしてください',
  heygenAvatarErrorVideoTooLarge: '動画は50MB以下にしてください',
  heygenAvatarErrorNoImage: '写真をアップロードしてください',
  heygenAvatarErrorNoFile: 'ファイルをアップロードしてください',
  heygenAvatarCreateNote: 'アバターはHeyGenにアップロードされ、即座に登録されます。写真アバターは動画生成のトーキングフォトとして使用できます。',
  heygenAvatarCancel: 'キャンセル',
  heygenAvatarCreatedToast: 'アバターを作成しました',
  heygenAvatarCreateFailed: 'アバターの作成に失敗しました',
  heygenAvatarErrorEmpty: '名前は必須です',
  heygenAvatarLoadFailed: 'アバター一覧の読み込みに失敗しました',
  heygenAvatarEmptyTitle: 'アバターがまだありません',
  heygenAvatarEmptyHint: '「新規アバター」をクリックして最初のカスタムHeyGenアバターを作成しましょう。',
  heygenAvatarRefresh: '更新',
  heygenAvatarDelete: '削除',
  heygenAvatarDeleteConfirm: 'このアバターを削除しますか？',
  heygenAvatarDeletedToast: 'アバターを削除しました',
  heygenAvatarDeleteFailed: 'アバターの削除に失敗しました',
  heygenAvatarRefreshFailed: '更新に失敗しました',
  heygenAvatarReadyToast: 'アバターの準備が完了しました',
  heygenAvatarStatusPENDING: '待機中',
  heygenAvatarStatusUPLOADING: 'アップロード中',
  heygenAvatarStatusTRAINING: 'トレーニング中',
  heygenAvatarStatusREADY: '完了',
  heygenAvatarStatusFAILED: '失敗',
  heygenAvatarRetry: '再試行',
  heygenAvatarRetryStarted: 'アバターの作成を再試行中…',
  heygenAvatarRetryFailed: '再試行に失敗しました',
  heygenAvatarApiMissingTitle: 'HeyGen APIキーが必要です',
  heygenAvatarApiMissingDesc: 'アバターを作成する前に、設定でHeyGen APIキーを設定してください。',
  heygenAvatarOpenSettings: '設定を開く',
  voicePreviewFailed: '音声プレビューに失敗しました',
  vsVoiceMale: '男性',
  vsVoiceFemale: '女性',
};

const translations: Record<Lang, Record<TKey, string>> = { en, ja };

interface LanguageContextValue {
  lang: Lang;
  toggle: () => void;
  t: (key: TKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ja');

  function toggle() {
    setLang((l) => (l === 'en' ? 'ja' : 'en'));
  }

  function t(key: TKey): string {
    return translations[lang][key];
  }

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
